#!/usr/bin/env python3
"""Write _downloads.md, the download card on the landing page, from the
GitHub Releases API.

The stable build is the newest published release that is not a pre-release;
the preview build is the newest pre-release published after it. The card
names both so the site never points at a stale version, and CI regenerates
the file on every push to main and every published release. The committed
copy is a snapshot that keeps a render working when the API is unreachable.

Usage: python3 docs/site/fetch_downloads.py   (GITHUB_TOKEN optional)
"""
from __future__ import annotations

import json
import os
import sys
import urllib.request
from pathlib import Path

REPO = "dhoconno/lungfish-genome-explorer"
OUT = Path(__file__).with_name("_downloads.md")
MANUAL_URL = "https://lungfish-genome-explorer.readthedocs.io/en/latest/"
SOURCE_URL = f"https://github.com/{REPO}"
RELEASES_URL = f"{SOURCE_URL}/releases"


def fetch_releases() -> list[dict]:
    request = urllib.request.Request(
        f"https://api.github.com/repos/{REPO}/releases?per_page=50",
        headers={
            "Accept": "application/vnd.github+json",
            "User-Agent": "lungfish-site-downloads",
        },
    )
    token = os.environ.get("GITHUB_TOKEN")
    if token:
        request.add_header("Authorization", f"Bearer {token}")
    with urllib.request.urlopen(request, timeout=30) as response:
        return json.load(response)


def pick(releases: list[dict]) -> tuple[dict, dict | None]:
    published = [r for r in releases if not r.get("draft") and r.get("published_at")]
    published.sort(key=lambda r: r["published_at"], reverse=True)
    stable = next(r for r in published if not r["prerelease"])
    preview = next(
        (
            r
            for r in published
            if r["prerelease"] and r["published_at"] > stable["published_at"]
        ),
        None,
    )
    return stable, preview


def version(release: dict) -> str:
    return release["tag_name"].removeprefix("v")


def download_url(release: dict) -> str:
    for asset in release.get("assets", []):
        if asset["name"].endswith(".dmg"):
            return asset["browser_download_url"]
    return release["html_url"]


def render(stable: dict, preview: dict | None) -> str:
    lines = [
        "<!-- AUTO-GENERATED by fetch_downloads.py from the GitHub Releases API. "
        "Do not edit by hand; CI rewrites this file on every publish. -->",
        "",
        f"**Download.** The current stable release is "
        f"[{version(stable)}]({download_url(stable)}).",
    ]
    if preview is not None:
        lines.append(
            f"If you would rather try new features first, the preview is "
            f"[{version(preview)}]({download_url(preview)}). It changes more often "
            f"and is more likely to surprise you."
        )
    lines.append(
        "Both channels ship as signed, notarized disk images for Apple Silicon Macs "
        "running macOS 26 Tahoe or later."
        if preview is not None
        else "It ships as a signed, notarized disk image for Apple Silicon Macs "
        "running macOS 26 Tahoe or later."
    )
    lines.append("")
    lines.append(
        f"Read the [user manual]({MANUAL_URL}), browse the [source code]({SOURCE_URL}), "
        f"or see [every release]({RELEASES_URL})."
    )
    return "\n".join(lines) + "\n"


def main() -> int:
    try:
        stable, preview = pick(fetch_releases())
    except Exception as error:  # noqa: BLE001 - any failure keeps the snapshot
        print(f"fetch_downloads: {error}", file=sys.stderr)
        return 1
    OUT.write_text(render(stable, preview), encoding="utf-8")
    print(f"fetch_downloads: stable {version(stable)}, "
          f"preview {version(preview) if preview else 'none newer than stable'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
