// AlignmentMarkdupPipeline.swift - Compatibility shims for workflow-owned markdup pipeline
// Copyright (c) 2024 Lungfish Contributors
// SPDX-License-Identifier: MIT

import LungfishWorkflow

public typealias AlignmentSamtoolsRunning = LungfishWorkflow.AlignmentSamtoolsRunning
public typealias NativeToolSamtoolsRunner = LungfishWorkflow.NativeToolSamtoolsRunner
public typealias AlignmentCommandExecutionRecord = LungfishWorkflow.AlignmentCommandExecutionRecord
public typealias AlignmentMarkdupIntermediateFiles = LungfishWorkflow.AlignmentMarkdupIntermediateFiles
public typealias AlignmentMarkdupPipelineResult = LungfishWorkflow.AlignmentMarkdupPipelineResult
public typealias AlignmentMarkdupPipelining = LungfishWorkflow.AlignmentMarkdupPipelining
public typealias AlignmentMarkdupPipeline = LungfishWorkflow.AlignmentMarkdupPipeline
public typealias AlignmentMarkdupPipelineError = LungfishWorkflow.AlignmentMarkdupPipelineError
