// MetagenomicsBatchResultStore.swift - App compatibility aliases for workflow batch sidecars
// Copyright (c) 2026 Lungfish Contributors
// SPDX-License-Identifier: MIT

import LungfishWorkflow

typealias MetagenomicsBatchSampleRecord = LungfishWorkflow.MetagenomicsBatchSampleRecord
typealias MetagenomicsBatchManifestHeader = LungfishWorkflow.MetagenomicsBatchManifestHeader
typealias ClassificationBatchResultManifest = LungfishWorkflow.ClassificationBatchResultManifest
typealias EsVirituBatchResultManifest = LungfishWorkflow.EsVirituBatchResultManifest
typealias TaxTriageCrossRef = LungfishWorkflow.TaxTriageCrossRef
typealias TaxTriageBatchManifest = LungfishWorkflow.TaxTriageBatchManifest
typealias EsVirituBatchAggregatedManifest = LungfishWorkflow.EsVirituBatchAggregatedManifest
typealias MetagenomicsBatchResultStore = LungfishWorkflow.MetagenomicsBatchResultStore
