#!/usr/bin/env nextflow
/*
 * lungfish map
 * Generated by Lungfish 2026.9.52 (1)
 * Original run: 2026-09-21T14:13:20Z
 * Host: macOS 26.6.2 (arm64)
 * 
 * These inputs were outside the project when the run was recorded, so
 * their paths are the recording machine's. Point each at your own copy:
 *   /data/inputs/reference.fasta
 *   /data/inputs/reads_R1.fastq.gz
 *   /data/inputs/reads_R2.fastq.gz
 *
 * Each process stages its inputs by file name and runs the recorded
 * command on them. Managed tools carry their recorded conda pin; run
 * with `nextflow run main.nf` (conda.enabled is set in nextflow.config).
 */

nextflow.enable.dsl = 2

// Pipeline parameters. Relative paths are resolved against the
// .lungfish project named by params.project.
params.project = '.'
params.reference_fasta = '/data/inputs/reference.fasta'
params.reads_r1_fastq_gz = '/data/inputs/reads_R1.fastq.gz'
params.reads_r2_fastq_gz = '/data/inputs/reads_R2.fastq.gz'
params.outdir = './results'

def projectFile(path) {
    path.startsWith('/') ? path : "${params.project}/${path}"
}

/*
 * Step 1: lungfish import fasta v2026.9.52 (1)
 * Original wall time: 0.2s
 */
process LUNGFISH_IMPORT_FASTA_1 {
    publishDir params.outdir, mode: 'copy'

    input:
    path 'reference.fasta'

    output:
    path 'sequence.fa.gz'

    script:
    "lungfish-cli import fasta reference.fasta --output-dir . --name reference"

    stub:
    "touch sequence.fa.gz"
}

/*
 * Step 2: bgzip v1.24
 * Original wall time: 0.1s
 */
process BGZIP_2 {
    publishDir params.outdir, mode: 'copy'

    input:
    path 'reference.fasta'

    output:
    path 'sequence.fa.gz'

    script:
    "bgzip -f sequence.fa"

    stub:
    "touch sequence.fa.gz"
}

/*
 * Step 3: samtools v1.24
 * Original wall time: 0.1s
 */
process SAMTOOLS_3 {
    publishDir params.outdir, mode: 'copy'

    input:
    path 'sequence.fa.gz'

    output:
    path 'sequence.fa.gz.fai'
    path 'sequence.fa.gz.gzi'

    script:
    "samtools faidx sequence.fa.gz"

    stub:
    "touch sequence.fa.gz.fai sequence.fa.gz.gzi"
}

/*
 * Step 4: clumpify.sh v40.02
 * Original wall time: 0.7s
 */
process CLUMPIFYSH_4 {
    publishDir params.outdir, mode: 'copy'

    input:
    path 'reads_R1.fastq.gz'
    path 'reads_R2.fastq.gz'

    output:
    path 'reads.fastq.gz'

    script:
    "clumpify.sh in=reads_R1.fastq.gz in2=reads_R2.fastq.gz out=reads.fastq.gz interleaved=t"

    stub:
    "touch reads.fastq.gz"
}

/*
 * Step 5: lungfish import fastq v2026.9.52 (1)
 * Original wall time: 0.0s
 */
process LUNGFISH_IMPORT_FASTQ_5 {
    publishDir params.outdir, mode: 'copy'

    input:
    path 'reads_R1.fastq.gz'
    path 'reads_R2.fastq.gz'

    output:
    path 'reads.fastq.gz'

    script:
    "lungfish-cli import fastq reads_R1.fastq.gz reads_R2.fastq.gz --project . --recipe none"

    stub:
    "touch reads.fastq.gz"
}

/*
 * Step 6: minimap2 v2.31
 * Original wall time: 0.7s
 */
process MINIMAP2_6 {
    conda 'bioconda::minimap2=2.31'
    publishDir params.outdir, mode: 'copy'

    input:
    path 'reads.fastq.gz'
    path 'sequence.fa.gz'

    output:
    path 'reads.raw.sam'

    script:
    "minimap2 -a -x sr -o reads.raw.sam sequence.fa.gz reads.fastq.gz"

    stub:
    "touch reads.raw.sam"
}

/*
 * Step 7: samtools v1.24
 * Original wall time: 0.7s
 */
process SAMTOOLS_7 {
    publishDir params.outdir, mode: 'copy'

    input:
    path 'reads.raw.sam'

    output:
    path 'reads.filtered.bam'

    script:
    "samtools view -b -o reads.filtered.bam -F 256 reads.raw.sam"

    stub:
    "touch reads.filtered.bam"
}

/*
 * Step 8: samtools v1.24
 * Original wall time: 0.1s
 */
process SAMTOOLS_8 {
    publishDir params.outdir, mode: 'copy'

    input:
    path 'reads.filtered.bam'

    output:
    path 'reads.sorted.bam'

    script:
    "samtools sort -o reads.sorted.bam reads.filtered.bam"

    stub:
    "touch reads.sorted.bam"
}

/*
 * Step 9: samtools v1.24
 * Original wall time: 0.0s
 */
process SAMTOOLS_9 {
    publishDir params.outdir, mode: 'copy'

    input:
    path 'reads.sorted.bam'

    output:
    path 'reads.sorted.bam.bai'

    script:
    "samtools index reads.sorted.bam"

    stub:
    "touch reads.sorted.bam.bai"
}

/*
 * Step 10: samtools v1.24
 * Original wall time: 0.0s
 */
process SAMTOOLS_10 {
    publishDir params.outdir, mode: 'copy'

    input:
    path 'reads.sorted.bam'

    output:
    path 'reads.sorted.bam.bai'
    path 'mapping-result.json'
    path 'sequence.fa.gz'
    path 'sequence.fa.gz.fai'
    path 'sequence.fa.gz.gzi'
    path 'manifest.json'
    path 'reads.fastq.gz'

    script:
    "samtools flagstat reads.sorted.bam"

    stub:
    "touch reads.sorted.bam.bai mapping-result.json sequence.fa.gz sequence.fa.gz.fai sequence.fa.gz.gzi manifest.json reads.fastq.gz"
}

// Main workflow
workflow {
    reference_fasta_ch = channel.fromPath(projectFile(params.reference_fasta))
    reads_r1_fastq_gz_ch = channel.fromPath(projectFile(params.reads_r1_fastq_gz))
    reads_r2_fastq_gz_ch = channel.fromPath(projectFile(params.reads_r2_fastq_gz))

    LUNGFISH_IMPORT_FASTA_1(reference_fasta_ch)
    BGZIP_2(reference_fasta_ch)
    SAMTOOLS_3(BGZIP_2.out[0])
    CLUMPIFYSH_4(reads_r1_fastq_gz_ch, reads_r2_fastq_gz_ch)
    LUNGFISH_IMPORT_FASTQ_5(reads_r1_fastq_gz_ch, reads_r2_fastq_gz_ch)
    MINIMAP2_6(LUNGFISH_IMPORT_FASTQ_5.out[0], BGZIP_2.out[0])
    SAMTOOLS_7(MINIMAP2_6.out[0])
    SAMTOOLS_8(SAMTOOLS_7.out[0])
    SAMTOOLS_9(SAMTOOLS_8.out[0])
    SAMTOOLS_10(SAMTOOLS_8.out[0])
}
