#!/usr/bin/env nextflow
/*
 * lungfish map
 * Generated by Lungfish 2026.9.52 (1)
 * Original run: 2026-09-21T14:13:20Z
 * Host: macOS 26.6.2 (arm64)
 */

nextflow.enable.dsl = 2

// Pipeline parameters
params.reference_fasta = 'reference.fasta'
params.reads_r1_fastq_gz = 'reads_R1.fastq.gz'
params.reads_r2_fastq_gz = 'reads_R2.fastq.gz'
params.outdir = './results'

/*
 * Step 1: lungfish import fasta Lungfish 2026.9.52 (1)
 * Original wall time: 0.2s
 */
process LUNGFISH_IMPORT_FASTA_1 {
    publishDir params.outdir, mode: 'copy'

    input:
    path 'reference.fasta'

    output:
    path 'sequence.fa.gz'

    script:
    "lungfish-cli import fasta /data/inputs/reference.fasta --output-dir /data/project --name reference"

    stub:
    "touch sequence.fa.gz"
}

/*
 * Step 2: bgzip 1.24
 * Original wall time: 0.1s
 */
process BGZIP_2 {
    publishDir params.outdir, mode: 'copy'

    input:
    path 'reference.fasta'

    output:
    path 'sequence.fa.gz'

    script:
    "/tools/bgzip -f '/data/project/Reference Sequences/reference.lungfishref/genome/sequence.fa'"

    stub:
    "touch sequence.fa.gz"
}

/*
 * Step 3: samtools 1.24
 * Original wall time: 0.1s
 */
process SAMTOOLS_3 {
    publishDir params.outdir, mode: 'copy'

    input:
    path 'sequence.fa.gz'

    output:
    path 'sequence.fa.gz.fai'
    path 'sequence.fa.gz.gzi'

    script:
    "/tools/samtools faidx '/data/project/Reference Sequences/reference.lungfishref/genome/sequence.fa.gz'"

    stub:
    "touch sequence.fa.gz.fai sequence.fa.gz.gzi"
}

/*
 * Step 4: clumpify.sh 40.02
 * Original wall time: 0.7s
 */
process CLUMPIFYSH_4 {
    publishDir params.outdir, mode: 'copy'

    input:
    path 'reads_R1.fastq.gz'
    path 'reads_R2.fastq.gz'

    output:
    path 'reads.fastq.gz'

    script:
    "/tools/clumpify.sh in=/data/inputs/reads_R1.fastq.gz in2=/data/inputs/reads_R2.fastq.gz out=/data/project/Imports/reads.lungfishfastq/reads.fastq.gz interleaved=t"

    stub:
    "touch reads.fastq.gz"
}

/*
 * Step 5: lungfish import fastq Lungfish 2026.9.52 (1)
 * Original wall time: 0.0s
 */
process LUNGFISH_IMPORT_FASTQ_5 {
    publishDir params.outdir, mode: 'copy'

    input:
    path 'reads_R1.fastq.gz'
    path 'reads_R2.fastq.gz'

    output:
    path 'reads.fastq.gz'

    script:
    "lungfish-cli import fastq /data/inputs/reads_R1.fastq.gz /data/inputs/reads_R2.fastq.gz --project /data/project --recipe none"

    stub:
    "touch reads.fastq.gz"
}

/*
 * Step 6: minimap2 2.31
 * Original wall time: 0.7s
 */
process MINIMAP2_6 {
    publishDir params.outdir, mode: 'copy'

    input:
    path 'reads.fastq.gz'
    path 'sequence.fa.gz'

    output:
    path 'reads.raw.sam'

    script:
    "micromamba run -n minimap2 minimap2 -a -x sr -o /data/project/Analyses/minimap2/reads.raw.sam '/data/project/Reference Sequences/reference.lungfishref/genome/sequence.fa.gz' /data/project/Imports/reads.lungfishfastq/reads.fastq.gz"

    stub:
    "touch reads.raw.sam"
}

/*
 * Step 7: samtools 1.24
 * Original wall time: 0.7s
 */
process SAMTOOLS_7 {
    publishDir params.outdir, mode: 'copy'

    input:
    path 'reads.raw.sam'

    output:
    path 'reads.filtered.bam'

    script:
    "/tools/samtools view -b -o /data/project/Analyses/minimap2/reads.filtered.bam -F 256 /data/project/Analyses/minimap2/reads.raw.sam"

    stub:
    "touch reads.filtered.bam"
}

/*
 * Step 8: samtools 1.24
 * Original wall time: 0.1s
 */
process SAMTOOLS_8 {
    publishDir params.outdir, mode: 'copy'

    input:
    path 'reads.filtered.bam'

    output:
    path 'reads.sorted.bam'

    script:
    "/tools/samtools sort -o /data/project/Analyses/minimap2/reads.sorted.bam /data/project/Analyses/minimap2/reads.filtered.bam"

    stub:
    "touch reads.sorted.bam"
}

/*
 * Step 9: samtools 1.24
 * Original wall time: 0.0s
 */
process SAMTOOLS_9 {
    publishDir params.outdir, mode: 'copy'

    input:
    path 'reads.sorted.bam'

    output:
    path 'reads.sorted.bam.bai'

    script:
    "/tools/samtools index /data/project/Analyses/minimap2/reads.sorted.bam"

    stub:
    "touch reads.sorted.bam.bai"
}

/*
 * Step 10: samtools 1.24
 * Original wall time: 0.0s
 */
process SAMTOOLS_10 {
    publishDir params.outdir, mode: 'copy'

    input:
    path 'reads.sorted.bam'

    output:
    path 'reads.sorted.bam.bai'
    path 'mapping-result.json'
    path 'sequence.fa.gz'
    path 'sequence.fa.gz.fai'
    path 'sequence.fa.gz.gzi'
    path 'manifest.json'
    path 'reads.fastq.gz'

    script:
    "/tools/samtools flagstat /data/project/Analyses/minimap2/reads.sorted.bam"

    stub:
    "touch reads.sorted.bam.bai mapping-result.json sequence.fa.gz sequence.fa.gz.fai sequence.fa.gz.gzi manifest.json reads.fastq.gz"
}

// Main workflow
workflow {
    reference_fasta_ch = channel.fromPath(params.reference_fasta)
    reads_r1_fastq_gz_ch = channel.fromPath(params.reads_r1_fastq_gz)
    reads_r2_fastq_gz_ch = channel.fromPath(params.reads_r2_fastq_gz)

    LUNGFISH_IMPORT_FASTA_1(reference_fasta_ch)
    BGZIP_2(reference_fasta_ch)
    SAMTOOLS_3(BGZIP_2.out[0])
    CLUMPIFYSH_4(reads_r1_fastq_gz_ch, reads_r2_fastq_gz_ch)
    LUNGFISH_IMPORT_FASTQ_5(reads_r1_fastq_gz_ch, reads_r2_fastq_gz_ch)
    MINIMAP2_6(LUNGFISH_IMPORT_FASTQ_5.out[0], BGZIP_2.out[0])
    SAMTOOLS_7(MINIMAP2_6.out[0])
    SAMTOOLS_8(SAMTOOLS_7.out[0])
    SAMTOOLS_9(SAMTOOLS_8.out[0])
    SAMTOOLS_10(SAMTOOLS_8.out[0])
}
