# lungfish map
# Generated by Lungfish 2026.9.52 (1)
# Original run: 2026-09-21T14:13:20Z
# Host: macOS 26.6.2 (arm64)
#
# Usage: snakemake --cores 8 --use-singularity

configfile: "config.yaml"

rule all:
    input:
        "/data/project/Reference Sequences/reference.lungfishref/genome/sequence.fa.gz.fai",
        "/data/project/Reference Sequences/reference.lungfishref/genome/sequence.fa.gz.gzi",
        "/data/project/Analyses/minimap2/reads.sorted.bam.bai",
        "/data/project/Analyses/minimap2/mapping-result.json",
        "/data/project/Reference Sequences/reference.lungfishref/manifest.json",


# Step 1: lungfish import fasta Lungfish 2026.9.52 (1)
# Original wall time: 0.2s
rule lungfish_import_fasta_1:
    input:
        "/data/inputs/reference.fasta",
    output:
        "/data/project/Reference Sequences/reference.lungfishref/genome/sequence.fa.gz",
    log:
        "logs/lungfish_import_fasta_1.log"
    shell:
        "mkdir -p \"$(dirname {log:q})\"\nlungfish-cli import fasta /data/inputs/reference.fasta --output-dir /data/project --name reference 2> {log:q}"

# Step 2: bgzip 1.24
# Original wall time: 0.1s
rule bgzip_2:
    input:
        "/data/inputs/reference.fasta",
    log:
        "logs/bgzip_2.log"
    shell:
        "mkdir -p \"$(dirname {log:q})\"\n/tools/bgzip -f '/data/project/Reference Sequences/reference.lungfishref/genome/sequence.fa' 2> {log:q}"

# Step 3: samtools 1.24
# Original wall time: 0.1s
rule samtools_3:
    input:
        "/data/project/Reference Sequences/reference.lungfishref/genome/sequence.fa.gz",
    output:
        "/data/project/Reference Sequences/reference.lungfishref/genome/sequence.fa.gz.fai",
        "/data/project/Reference Sequences/reference.lungfishref/genome/sequence.fa.gz.gzi",
    log:
        "logs/samtools_3.log"
    shell:
        "mkdir -p \"$(dirname {log:q})\"\n/tools/samtools faidx '/data/project/Reference Sequences/reference.lungfishref/genome/sequence.fa.gz' 2> {log:q}"

# Step 4: clumpify.sh 40.02
# Original wall time: 0.7s
rule clumpifysh_4:
    input:
        "/data/inputs/reads_R1.fastq.gz",
        "/data/inputs/reads_R2.fastq.gz",
    output:
        "/data/project/Imports/reads.lungfishfastq/reads.fastq.gz",
    log:
        "logs/clumpifysh_4.log"
    shell:
        "mkdir -p \"$(dirname {log:q})\"\n/tools/clumpify.sh in=/data/inputs/reads_R1.fastq.gz in2=/data/inputs/reads_R2.fastq.gz out=/data/project/Imports/reads.lungfishfastq/reads.fastq.gz interleaved=t 2> {log:q}"

# Step 5: lungfish import fastq Lungfish 2026.9.52 (1)
# Original wall time: 0.0s
rule lungfish_import_fastq_5:
    input:
        "/data/inputs/reads_R1.fastq.gz",
        "/data/inputs/reads_R2.fastq.gz",
    log:
        "logs/lungfish_import_fastq_5.log"
    shell:
        "mkdir -p \"$(dirname {log:q})\"\nlungfish-cli import fastq /data/inputs/reads_R1.fastq.gz /data/inputs/reads_R2.fastq.gz --project /data/project --recipe none 2> {log:q}"

# Step 6: minimap2 2.31
# Original wall time: 0.7s
rule minimap2_6:
    input:
        "/data/project/Imports/reads.lungfishfastq/reads.fastq.gz",
        "/data/project/Reference Sequences/reference.lungfishref/genome/sequence.fa.gz",
    output:
        "/data/project/Analyses/minimap2/reads.raw.sam",
    log:
        "logs/minimap2_6.log"
    shell:
        "mkdir -p \"$(dirname {log:q})\"\nmicromamba run -n minimap2 minimap2 -a -x sr -o /data/project/Analyses/minimap2/reads.raw.sam '/data/project/Reference Sequences/reference.lungfishref/genome/sequence.fa.gz' /data/project/Imports/reads.lungfishfastq/reads.fastq.gz 2> {log:q}"

# Step 7: samtools 1.24
# Original wall time: 0.7s
rule samtools_7:
    input:
        "/data/project/Analyses/minimap2/reads.raw.sam",
    output:
        "/data/project/Analyses/minimap2/reads.filtered.bam",
    log:
        "logs/samtools_7.log"
    shell:
        "mkdir -p \"$(dirname {log:q})\"\n/tools/samtools view -b -o /data/project/Analyses/minimap2/reads.filtered.bam -F 256 /data/project/Analyses/minimap2/reads.raw.sam 2> {log:q}"

# Step 8: samtools 1.24
# Original wall time: 0.1s
rule samtools_8:
    input:
        "/data/project/Analyses/minimap2/reads.filtered.bam",
    output:
        "/data/project/Analyses/minimap2/reads.sorted.bam",
    log:
        "logs/samtools_8.log"
    shell:
        "mkdir -p \"$(dirname {log:q})\"\n/tools/samtools sort -o /data/project/Analyses/minimap2/reads.sorted.bam /data/project/Analyses/minimap2/reads.filtered.bam 2> {log:q}"

# Step 9: samtools 1.24
# Original wall time: 0.0s
rule samtools_9:
    input:
        "/data/project/Analyses/minimap2/reads.sorted.bam",
    output:
        "/data/project/Analyses/minimap2/reads.sorted.bam.bai",
    log:
        "logs/samtools_9.log"
    shell:
        "mkdir -p \"$(dirname {log:q})\"\n/tools/samtools index /data/project/Analyses/minimap2/reads.sorted.bam 2> {log:q}"

# Step 10: samtools 1.24
# Original wall time: 0.0s
rule samtools_10:
    input:
        "/data/project/Analyses/minimap2/reads.sorted.bam",
    output:
        "/data/project/Analyses/minimap2/mapping-result.json",
        "/data/project/Reference Sequences/reference.lungfishref/manifest.json",
    log:
        "logs/samtools_10.log"
    shell:
        "mkdir -p \"$(dirname {log:q})\"\n/tools/samtools flagstat /data/project/Analyses/minimap2/reads.sorted.bam 2> {log:q}"

