# lungfish map
# Generated by Lungfish 2026.9.52 (1)
# Original run: 2026-09-21T14:13:20Z
# Host: macOS 26.6.2 (arm64)
# 
# These inputs were outside the project when the run was recorded, so
# their paths are the recording machine's. Point each at your own copy:
#   /data/inputs/reference.fasta
#   /data/inputs/reads_R1.fastq.gz
#   /data/inputs/reads_R2.fastq.gz
#
# Inputs are read from the .lungfish project named by config['project']
# (default: the working directory). Managed tools are recreated from
# the recorded package pins in envs/.
#
# Usage: snakemake --cores 8 --software-deployment-method conda \
#            --directory "/path/to/Project.lungfish"

import os

configfile: os.path.join(workflow.basedir, "config.yaml")


def project(relative):
    """A file inside the .lungfish project, or an absolute path as given."""
    return os.path.normpath(os.path.join(config.get("project", "."), relative))


rule all:
    input:
        project("Reference Sequences/reference.lungfishref/genome/sequence.fa.gz.fai"),
        project("Reference Sequences/reference.lungfishref/genome/sequence.fa.gz.gzi"),
        project("Analyses/minimap2/reads.sorted.bam.bai"),
        project("Analyses/minimap2/mapping-result.json"),
        project("Reference Sequences/reference.lungfishref/manifest.json"),


# Step 1: lungfish import fasta v2026.9.52 (1)
# Original wall time: 0.2s
rule lungfish_import_fasta_1:
    input:
        reference_fasta=project(config["reference_fasta"]),
    output:
        sequence_fa_gz=project("Reference Sequences/reference.lungfishref/genome/sequence.fa.gz"),
    log:
        "logs/lungfish_import_fasta_1.log"
    shell:
        "mkdir -p \"$(dirname {log:q})\"\nlungfish-cli import fasta \"{input.reference_fasta}\" --output-dir \"{config[project]}\" --name reference 2> {log:q}"

# Step 2: bgzip v1.24
# Original wall time: 0.1s
rule bgzip_2:
    input:
        reference_fasta=project(config["reference_fasta"]),
    log:
        "logs/bgzip_2.log"
    shell:
        "mkdir -p \"$(dirname {log:q})\"\nbgzip -f \"{config[project]}/Reference Sequences/reference.lungfishref/genome/sequence.fa\" 2> {log:q}"

# Step 3: samtools v1.24
# Original wall time: 0.1s
rule samtools_3:
    input:
        sequence_fa_gz=project("Reference Sequences/reference.lungfishref/genome/sequence.fa.gz"),
    output:
        sequence_fa_gz_fai=project("Reference Sequences/reference.lungfishref/genome/sequence.fa.gz.fai"),
        sequence_fa_gz_gzi=project("Reference Sequences/reference.lungfishref/genome/sequence.fa.gz.gzi"),
    log:
        "logs/samtools_3.log"
    shell:
        "mkdir -p \"$(dirname {log:q})\"\nsamtools faidx \"{input.sequence_fa_gz}\" 2> {log:q}"

# Step 4: clumpify.sh v40.02
# Original wall time: 0.7s
rule clumpifysh_4:
    input:
        reads_r1_fastq_gz=project(config["reads_r1_fastq_gz"]),
        reads_r2_fastq_gz=project(config["reads_r2_fastq_gz"]),
    output:
        reads_fastq_gz=project("Imports/reads.lungfishfastq/reads.fastq.gz"),
    log:
        "logs/clumpifysh_4.log"
    shell:
        "mkdir -p \"$(dirname {log:q})\"\nclumpify.sh \"in={input.reads_r1_fastq_gz}\" \"in2={input.reads_r2_fastq_gz}\" \"out={output.reads_fastq_gz}\" interleaved=t 2> {log:q}"

# Step 5: lungfish import fastq v2026.9.52 (1)
# Original wall time: 0.0s
rule lungfish_import_fastq_5:
    input:
        reads_r1_fastq_gz=project(config["reads_r1_fastq_gz"]),
        reads_r2_fastq_gz=project(config["reads_r2_fastq_gz"]),
    log:
        "logs/lungfish_import_fastq_5.log"
    shell:
        "mkdir -p \"$(dirname {log:q})\"\nlungfish-cli import fastq \"{input.reads_r1_fastq_gz}\" \"{input.reads_r2_fastq_gz}\" --project \"{config[project]}\" --recipe none 2> {log:q}"

# Step 6: minimap2 v2.31 (bioconda::minimap2=2.31)
# Original wall time: 0.7s
rule minimap2_6:
    input:
        reads_fastq_gz=project("Imports/reads.lungfishfastq/reads.fastq.gz"),
        sequence_fa_gz=project("Reference Sequences/reference.lungfishref/genome/sequence.fa.gz"),
    output:
        reads_raw_sam=project("Analyses/minimap2/reads.raw.sam"),
    log:
        "logs/minimap2_6.log"
    conda:
        "envs/minimap2.yaml"
    shell:
        "mkdir -p \"$(dirname {log:q})\"\nminimap2 -a -x sr -o \"{output.reads_raw_sam}\" \"{input.sequence_fa_gz}\" \"{input.reads_fastq_gz}\" 2> {log:q}"

# Step 7: samtools v1.24
# Original wall time: 0.7s
rule samtools_7:
    input:
        reads_raw_sam=project("Analyses/minimap2/reads.raw.sam"),
    output:
        reads_filtered_bam=project("Analyses/minimap2/reads.filtered.bam"),
    log:
        "logs/samtools_7.log"
    shell:
        "mkdir -p \"$(dirname {log:q})\"\nsamtools view -b -o \"{output.reads_filtered_bam}\" -F 256 \"{input.reads_raw_sam}\" 2> {log:q}"

# Step 8: samtools v1.24
# Original wall time: 0.1s
rule samtools_8:
    input:
        reads_filtered_bam=project("Analyses/minimap2/reads.filtered.bam"),
    output:
        reads_sorted_bam=project("Analyses/minimap2/reads.sorted.bam"),
    log:
        "logs/samtools_8.log"
    shell:
        "mkdir -p \"$(dirname {log:q})\"\nsamtools sort -o \"{output.reads_sorted_bam}\" \"{input.reads_filtered_bam}\" 2> {log:q}"

# Step 9: samtools v1.24
# Original wall time: 0.0s
rule samtools_9:
    input:
        reads_sorted_bam=project("Analyses/minimap2/reads.sorted.bam"),
    output:
        reads_sorted_bam_bai=project("Analyses/minimap2/reads.sorted.bam.bai"),
    log:
        "logs/samtools_9.log"
    shell:
        "mkdir -p \"$(dirname {log:q})\"\nsamtools index \"{input.reads_sorted_bam}\" 2> {log:q}"

# Step 10: samtools v1.24
# Original wall time: 0.0s
rule samtools_10:
    input:
        reads_sorted_bam=project("Analyses/minimap2/reads.sorted.bam"),
    output:
        mapping_result_json=project("Analyses/minimap2/mapping-result.json"),
        manifest_json=project("Reference Sequences/reference.lungfishref/manifest.json"),
    log:
        "logs/samtools_10.log"
    shell:
        "mkdir -p \"$(dirname {log:q})\"\nsamtools flagstat \"{input.reads_sorted_bam}\" 2> {log:q}"

