// ProvenanceExporter.swift - Export provenance records to reproducible scripts
// Copyright (c) 2024 Lungfish Contributors
// SPDX-License-Identifier: MIT

import Foundation

// MARK: - ProvenanceExportFormat

/// Supported provenance export formats.
public enum ProvenanceExportFormat: String, CaseIterable, Sendable {
    case shell = "Shell Script"
    case python = "Python Script"
    case nextflow = "Nextflow Pipeline"
    case snakemake = "Snakemake Workflow"
    case methods = "Methods Section"
    case json = "Full Provenance (JSON)"

    /// File extension for this export format.
    public var fileExtension: String {
        switch self {
        case .shell: return "sh"
        case .python: return "py"
        case .nextflow: return "nf"
        case .snakemake: return "smk"
        case .methods: return "txt"
        case .json: return "json"
        }
    }

    /// Default filename for this export format.
    public var defaultFilename: String {
        switch self {
        case .shell: return "reproduce.sh"
        case .python: return "reproduce.py"
        case .nextflow: return "main.nf"
        case .snakemake: return "Snakefile"
        case .methods: return "methods.txt"
        case .json: return "provenance.json"
        }
    }
}

// MARK: - ProvenanceExporter

/// Generates reproducible scripts from provenance records.
///
/// Each export method takes a `WorkflowRun` and produces a self-contained
/// script that can reproduce the analysis on any system with the same
/// tools installed (or via containers).
public struct ProvenanceExporter: Sendable {

    public init() {}

    /// Exports a workflow run in the specified format.
    public func export(_ run: WorkflowRun, format: ProvenanceExportFormat) throws -> String {
        switch format {
        case .shell: return exportShell(run)
        case .python: return exportPython(run)
        case .nextflow: return exportNextflow(run)
        case .snakemake: return exportSnakemake(run)
        case .methods: return exportMethods(run)
        case .json: return try exportJSON(run)
        }
    }

    // MARK: - Shell Script Export

    /// Generates a Bash script that reproduces the workflow.
    public func exportShell(_ run: WorkflowRun) -> String {
        var s = ""
        s += "#!/usr/bin/env bash\n"
        s += "#\n"
        s += "# \(run.name)\n"
        s += "# Generated by \(run.appVersion)\n"
        s += "# Original run: \(iso8601(run.startTime))\n"
        s += "# Host: \(run.hostOS)\n"
        s += "#\n"
        s += "# This script reproduces the analysis performed in Lungfish.\n"
        s += "# Ensure the required tools are installed or use the container\n"
        s += "# images specified in the comments.\n"
        s += "#\n"
        s += "set -euo pipefail\n\n"

        // Input files as variables
        let inputs = run.primaryInputFiles
        if !inputs.isEmpty {
            s += "# Input files\n"
            for (i, input) in inputs.enumerated() {
                let varName = "INPUT_\(i + 1)"
                s += "\(varName)=\"\(input.filename)\""
                if let sha = input.sha256 {
                    s += "  # sha256: \(sha)"
                }
                s += "\n"
            }
            s += "\n"
        }

        // Output directory
        s += "# Output directory\n"
        s += "OUTDIR=\"results\"\n"
        s += "mkdir -p \"$OUTDIR\"\n\n"

        // Each step
        for (i, step) in run.steps.enumerated() {
            s += "# Step \(i + 1): \(step.toolName) \(step.toolVersion)\n"
            if let image = step.containerImage {
                s += "# Container: \(image)\n"
                if let digest = step.containerDigest {
                    s += "# Digest: \(digest)\n"
                }
            }
            if let wallTime = step.wallTime {
                s += "# Wall time: \(formatDuration(wallTime))\n"
            }

            // Write the actual command
            s += shellCommand(step)
            s += "\n"
        }

        s += "echo \"Pipeline complete.\"\n"
        return s
    }

    private func shellCommand(_ step: StepExecution) -> String {
        // Reconstruct the command, skipping the absolute tool path
        // and using just the tool name for portability
        var args = step.command
        if !args.isEmpty {
            // Replace absolute path with tool name
            let firstArg = args[0]
            if firstArg.contains("/") {
                args[0] = URL(fileURLWithPath: firstArg).lastPathComponent
            }
        }
        return args.map { shellEscape($0) }.joined(separator: " \\\n    ") + "\n"
    }

    // MARK: - Python Script Export

    /// Generates a Python script using subprocess to reproduce the workflow.
    public func exportPython(_ run: WorkflowRun) -> String {
        var s = ""
        s += "#!/usr/bin/env python3\n"
        s += "\"\"\"\n"
        s += "\(run.name)\n"
        s += "Generated by \(run.appVersion)\n"
        s += "Original run: \(iso8601(run.startTime))\n"
        s += "Host: \(run.hostOS)\n"
        s += "\n"
        s += "This script reproduces the analysis performed in Lungfish.\n"
        s += "\"\"\"\n\n"
        s += "import subprocess\n"
        s += "import sys\n"
        s += "import os\n"
        s += "from pathlib import Path\n\n"

        // Input files
        let inputs = run.primaryInputFiles
        if !inputs.isEmpty {
            s += "# Input files\n"
            s += "INPUTS = {\n"
            for input in inputs {
                s += "    \"\(input.filename)\": \"\(input.sha256 ?? "unknown")\",  # sha256\n"
            }
            s += "}\n\n"
        }

        s += "OUTDIR = Path(\"results\")\n"
        s += "OUTDIR.mkdir(exist_ok=True)\n\n"

        s += "def run_step(name: str, cmd: list[str]) -> None:\n"
        s += "    \"\"\"Run a pipeline step and check for errors.\"\"\"\n"
        s += "    print(f\"Running: {name}\")\n"
        s += "    result = subprocess.run(cmd, capture_output=True, text=True)\n"
        s += "    if result.returncode != 0:\n"
        s += "        print(f\"ERROR in {name}: {result.stderr}\", file=sys.stderr)\n"
        s += "        sys.exit(result.returncode)\n"
        s += "    print(f\"  Done ({name})\")\n\n\n"

        // Steps
        for (i, step) in run.steps.enumerated() {
            let stepName = "step_\(i + 1)_\(sanitize(step.toolName))"
            s += "def \(stepName)():\n"
            s += "    \"\"\"\(step.toolName) \(step.toolVersion)"
            if let image = step.containerImage {
                s += " (container: \(image))"
            }
            s += "\"\"\"\n"

            // Build command list
            var args = step.command
            if !args.isEmpty && args[0].contains("/") {
                args[0] = URL(fileURLWithPath: args[0]).lastPathComponent
            }
            let pyArgs = args.map { "\"\($0.replacingOccurrences(of: "\"", with: "\\\""))\"" }
            s += "    run_step(\"\(step.toolName)\", [\n"
            for arg in pyArgs {
                s += "        \(arg),\n"
            }
            s += "    ])\n\n\n"
        }

        // Main
        s += "if __name__ == \"__main__\":\n"
        s += "    print(\"Reproducing: \(run.name)\")\n"
        for (i, step) in run.steps.enumerated() {
            let stepName = "step_\(i + 1)_\(sanitize(step.toolName))"
            s += "    \(stepName)()\n"
        }
        s += "    print(\"Pipeline complete.\")\n"

        return s
    }

    // MARK: - Nextflow Export

    /// Generates a Nextflow DSL2 pipeline from the provenance record.
    public func exportNextflow(_ run: WorkflowRun) -> String {
        var s = ""
        s += "#!/usr/bin/env nextflow\n"
        s += "/*\n"
        s += " * \(run.name)\n"
        s += " * Generated by \(run.appVersion)\n"
        s += " * Original run: \(iso8601(run.startTime))\n"
        s += " * Host: \(run.hostOS)\n"
        s += " */\n\n"
        s += "nextflow.enable.dsl = 2\n\n"

        // Parameters from input files
        s += "// Pipeline parameters\n"
        s += "params {\n"
        let inputs = run.primaryInputFiles
        for input in inputs {
            let paramName = sanitize(input.filename.replacingOccurrences(of: ".", with: "_"))
            s += "    \(paramName) = '\(input.filename)'\n"
        }
        s += "    outdir = './results'\n"
        s += "}\n\n"

        // Process definitions
        for (i, step) in run.steps.enumerated() {
            let processName = "\(sanitize(step.toolName).uppercased())_\(i + 1)"

            s += "/*\n"
            s += " * Step \(i + 1): \(step.toolName) \(step.toolVersion)\n"
            if let wallTime = step.wallTime {
                s += " * Original wall time: \(formatDuration(wallTime))\n"
            }
            s += " */\n"
            s += "process \(processName) {\n"

            if let image = step.containerImage {
                s += "    container '\(image)'\n"
            }

            s += "    publishDir params.outdir, mode: 'copy'\n\n"

            // Input
            if !step.inputs.isEmpty {
                s += "    input:\n"
                for input in step.inputs {
                    s += "    path '\(input.filename)'\n"
                }
                s += "\n"
            }

            // Output
            if !step.outputs.isEmpty {
                s += "    output:\n"
                for output in step.outputs {
                    s += "    path '\(output.filename)'\n"
                }
                s += "\n"
            }

            // Script
            s += "    script:\n"
            s += "    \"\"\"\n"
            s += "    \(portableCommand(step))\n"
            s += "    \"\"\"\n"
            s += "}\n\n"
        }

        // Workflow block
        s += "// Main workflow\n"
        s += "workflow {\n"

        // Create input channels
        for input in inputs {
            let paramName = sanitize(input.filename.replacingOccurrences(of: ".", with: "_"))
            let chName = "\(paramName)_ch"
            s += "    \(chName) = Channel.fromPath(params.\(paramName))\n"
        }
        s += "\n"

        // Chain processes
        for (i, step) in run.steps.enumerated() {
            let processName = "\(sanitize(step.toolName).uppercased())_\(i + 1)"
            if i == 0 && !inputs.isEmpty {
                let paramName = sanitize(inputs[0].filename.replacingOccurrences(of: ".", with: "_"))
                s += "    \(processName)(\(paramName)_ch)\n"
            } else if i > 0 {
                let prevName = "\(sanitize(run.steps[i - 1].toolName).uppercased())_\(i)"
                s += "    \(processName)(\(prevName).out)\n"
            } else {
                s += "    \(processName)()\n"
            }
        }

        s += "}\n"
        return s
    }

    // MARK: - Snakemake Export

    /// Generates a Snakefile from the provenance record.
    public func exportSnakemake(_ run: WorkflowRun) -> String {
        var s = ""
        s += "# \(run.name)\n"
        s += "# Generated by \(run.appVersion)\n"
        s += "# Original run: \(iso8601(run.startTime))\n"
        s += "# Host: \(run.hostOS)\n"
        s += "#\n"
        s += "# Usage: snakemake --cores 8 --use-singularity\n\n"

        s += "configfile: \"config.yaml\"\n\n"

        // Collect all final outputs
        let finalOutputs = run.steps.last?.outputs ?? []
        s += "rule all:\n"
        s += "    input:\n"
        for output in finalOutputs {
            s += "        \"results/\(output.filename)\",\n"
        }
        s += "\n\n"

        // Rule definitions
        for (i, step) in run.steps.enumerated() {
            let ruleName = "\(sanitize(step.toolName))_\(i + 1)"

            s += "# Step \(i + 1): \(step.toolName) \(step.toolVersion)\n"
            if let wallTime = step.wallTime {
                s += "# Original wall time: \(formatDuration(wallTime))\n"
            }

            s += "rule \(ruleName):\n"

            // Input
            s += "    input:\n"
            for input in step.inputs {
                if step.dependsOn.isEmpty {
                    s += "        \"\(input.filename)\",\n"
                } else {
                    s += "        \"results/\(input.filename)\",\n"
                }
            }

            // Output
            s += "    output:\n"
            for output in step.outputs {
                s += "        \"results/\(output.filename)\",\n"
            }

            // Log
            s += "    log:\n"
            s += "        \"logs/\(ruleName).log\"\n"

            // Container
            if let image = step.containerImage {
                s += "    singularity:\n"
                s += "        \"docker://\(image)\"\n"
            }

            // Shell
            s += "    shell:\n"
            s += "        \"\"\"\n"
            s += "        \(portableCommand(step)) 2> {log}\n"
            s += "        \"\"\"\n\n"
        }

        return s
    }

    // MARK: - Methods Section Export

    /// Generates publication-ready methods text from the provenance record.
    public func exportMethods(_ run: WorkflowRun) -> String {
        var s = ""
        s += "Methods\n"
        s += "=======\n\n"
        s += "Computational Analysis\n"
        s += "----------------------\n\n"

        // Group steps by tool for cleaner prose
        var toolSentences: [String] = []

        for step in run.steps where step.isSuccess {
            var sentence = ""

            // Build a methods sentence for this step
            let toolDesc = toolDescription(step.toolName)
            sentence += "\(toolDesc) was performed using \(step.toolName) v\(step.toolVersion)"

            // Add key parameters (non-path arguments)
            let keyParams = extractKeyParameters(step)
            if !keyParams.isEmpty {
                sentence += " with \(keyParams.joined(separator: ", "))"
            }

            sentence += "."

            // Add container provenance
            if let image = step.containerImage {
                sentence += " The tool was executed in a container (\(image)"
                if let digest = step.containerDigest {
                    sentence += ", digest: \(digest)"
                }
                sentence += ")."
            }

            toolSentences.append(sentence)
        }

        s += toolSentences.joined(separator: " ") + "\n\n"

        // Tool versions table
        s += "Tool Versions\n"
        s += "-------------\n\n"
        s += "| Tool | Version | Container |\n"
        s += "|------|---------|----------|\n"
        for step in run.steps where step.isSuccess {
            let container = step.containerImage ?? "native"
            s += "| \(step.toolName) | \(step.toolVersion) | \(container) |\n"
        }
        s += "\n"

        // Input files
        s += "Input Files\n"
        s += "-----------\n\n"
        for input in run.primaryInputFiles {
            s += "- \(input.filename)"
            if let sha = input.sha256 {
                s += " (SHA-256: \(sha))"
            }
            s += "\n"
        }
        s += "\n"

        // Reproducibility note
        s += "Reproducibility\n"
        s += "---------------\n\n"
        s += "This analysis was performed using \(run.appVersion) on \(run.hostOS). "
        s += "A machine-readable provenance record and executable pipeline scripts "
        s += "(Nextflow, Snakemake, and shell) are available in the supplementary materials.\n"

        return s
    }

    // MARK: - JSON Export

    /// Exports the full provenance record as formatted JSON.
    public func exportJSON(_ run: WorkflowRun) throws -> String {
        let encoder = JSONEncoder()
        encoder.dateEncodingStrategy = .iso8601
        encoder.outputFormatting = [.prettyPrinted, .sortedKeys]
        let data = try encoder.encode(run)
        guard let string = String(data: data, encoding: .utf8) else {
            throw ProvenanceError.exportFailed("Failed to encode JSON as UTF-8")
        }
        return string
    }

    // MARK: - Helpers

    private func iso8601(_ date: Date) -> String {
        ISO8601DateFormatter().string(from: date)
    }

    private func formatDuration(_ seconds: TimeInterval) -> String {
        if seconds < 60 {
            return String(format: "%.1fs", seconds)
        } else if seconds < 3600 {
            let mins = Int(seconds) / 60
            let secs = Int(seconds) % 60
            return "\(mins)m \(secs)s"
        } else {
            let hours = Int(seconds) / 3600
            let mins = (Int(seconds) % 3600) / 60
            return "\(hours)h \(mins)m"
        }
    }

    private func sanitize(_ name: String) -> String {
        var s = name.replacingOccurrences(of: " ", with: "_")
        s = s.replacingOccurrences(of: "-", with: "_")
        s = s.filter { $0.isLetter || $0.isNumber || $0 == "_" }
        if let first = s.first, first.isNumber {
            s = "_" + s
        }
        return s.lowercased()
    }

    private func shellEscape(_ arg: String) -> String {
        if arg.isEmpty { return "''" }
        if arg.allSatisfy({ $0.isLetter || $0.isNumber || "-._/=:@".contains($0) }) {
            return arg
        }
        return "'\(arg.replacingOccurrences(of: "'", with: "'\\''"))'"
    }

    /// Builds a portable command string (tool name instead of absolute path).
    private func portableCommand(_ step: StepExecution) -> String {
        var args = step.command
        if !args.isEmpty && args[0].contains("/") {
            args[0] = URL(fileURLWithPath: args[0]).lastPathComponent
        }
        return args.joined(separator: " ")
    }

    /// Returns a human-readable description of what a tool does.
    private func toolDescription(_ toolName: String) -> String {
        switch toolName.lowercased() {
        case "samtools": return "Alignment processing"
        case "bcftools": return "Variant processing"
        case "bgzip": return "Block compression"
        case "tabix": return "Indexing"
        case "bedtobigbed": return "BED to BigBed conversion"
        case "bedgraphtobigwig": return "Signal track conversion"
        case "fastp": return "Read quality filtering and trimming"
        case "fastqc": return "Sequence quality assessment"
        case "multiqc": return "Quality report aggregation"
        case "bwa": return "Short-read alignment"
        case "minimap2": return "Sequence alignment"
        case "spades", "spades.py": return "De novo genome assembly"
        case "seqkit": return "Sequence manipulation"
        case "vsearch": return "Sequence clustering"
        case "cutadapt": return "Adapter trimming"
        case "bbduk.sh", "bbduk": return "Quality filtering and adapter removal"
        case "bbmerge.sh", "bbmerge": return "Paired-end read merging"
        case "pigz": return "Parallel compression"
        default: return "Processing"
        }
    }

    /// Extracts human-readable key parameters from a step's command.
    private func extractKeyParameters(_ step: StepExecution) -> [String] {
        var params: [String] = []
        let args = step.command

        for i in 0..<args.count {
            let arg = args[i]

            // Skip the tool path and file arguments
            if i == 0 { continue }
            if !arg.hasPrefix("-") { continue }

            // Extract commonly reported parameters
            switch arg {
            case "-q", "--qualified_quality_phred":
                if i + 1 < args.count {
                    params.append("minimum quality score of \(args[i + 1])")
                }
            case "-l", "--length_required":
                if i + 1 < args.count {
                    params.append("minimum length of \(args[i + 1]) bp")
                }
            case "-t", "-@", "--threads":
                if i + 1 < args.count {
                    params.append("\(args[i + 1]) threads")
                }
            case "--memory":
                if i + 1 < args.count {
                    params.append("\(args[i + 1]) GB memory")
                }
            case "--isolate", "--meta", "--plasmid", "--rna":
                params.append("\(arg.dropFirst(2)) mode")
            default:
                break
            }
        }

        return params
    }
}
