import AppKit
import SwiftUI
import UniformTypeIdentifiers
import LungfishIO

struct PrimerDesignDialog: View {
  private struct InputLoadIdentity: Hashable {
    let urls: [URL]
    let revision: UInt64
  }
  @Bindable var state: PrimerDesignDialogState
  let onRun: () -> Void
  let onCancelRun: () -> Void
  let onClose: () -> Void
  let onOpenResult: (URL) -> Void

  var body: some View {
    VStack(spacing: 0) {
      HStack(alignment: .top) {
        VStack(alignment: .leading, spacing: 5) {
          Text("PCR Primer Design").font(.title2.bold())
          Text("Design from sequences or aligned MHC alleles, and keep the complete analysis.")
            .foregroundStyle(.secondary)
        }
        Spacer()
        Button("Manage Tools…") { PluginManagerWindowController.show(packID: "pcr-primer-design") }
      }.padding(20)
      Divider()
      HStack(spacing: 0) {
        VStack(alignment: .leading, spacing: 12) {
          ForEach(PrimerDesignEngine.allCases) { engine in
            Button { state.engine = engine } label: {
              VStack(alignment: .leading, spacing: 5) {
                Text(engine.rawValue).font(.headline)
                Text(engine == .primer3 ? "Primer pairs & qPCR probes" : "Tiled primer pool schemes")
                  .font(.caption).foregroundStyle(.secondary)
              }
              .frame(maxWidth: .infinity, alignment: .leading).padding(12)
              .background(state.engine == engine ? Color.accentColor.opacity(0.12) : .clear,
                          in: RoundedRectangle(cornerRadius: 8))
            }.buttonStyle(.plain)
          }
          Spacer()
          Text("MHC examples").font(.caption.bold()).foregroundStyle(.secondary)
          ForEach(PrimerDesignMHCExemplar.allCases) { example in
            Button(example.rawValue) { state.applyExemplar(example) }.buttonStyle(.link)
          }
          Text("Example names only. Choose full-length input sequences and appropriate design settings.")
            .font(.caption).foregroundStyle(.secondary)
        }.padding(16).frame(width: 220).background(.quaternary.opacity(0.2))
        Divider()
        ScrollView {
          VStack(alignment: .leading, spacing: 24) {
            inputSection
            if state.engine == .primer3 { primer3Section } else { schemeSection }
            advancedSection
            outputSection
          }.padding(24).frame(maxWidth: .infinity, alignment: .leading)
        }
      }.disabled(state.isRunning)
      Divider()
      footer.padding(16)
    }
    .frame(minWidth: 840, minHeight: 640)
    .background(Color(nsColor: .windowBackgroundColor))
    .task(id: InputLoadIdentity(urls: state.inputURLs, revision: state.inspectionRevision)) {
      await state.inspectInputs()
    }
  }

  private var inputSection: some View {
    VStack(alignment: .leading, spacing: 10) {
      HStack {
        Text("Inputs").font(.headline)
        Spacer()
        if !state.inputURLs.isEmpty {
          Button("Refresh", action: state.refreshInputs).disabled(state.isInspecting)
        }
        Button("Add FASTA or MSA…", action: chooseInputs)
      }
      if state.inputURLs.isEmpty {
        Text("Add one or more FASTA files or Lungfish alignments generated by MAFFT.")
          .foregroundStyle(.secondary)
      }
      ForEach(state.inputURLs, id: \.self) { url in
        VStack(alignment: .leading, spacing: 10) {
          HStack(alignment: .top, spacing: 10) {
          Image(systemName: "doc.text").foregroundStyle(.secondary)
          VStack(alignment: .leading, spacing: 3) {
            Text(url.deletingPathExtension().lastPathComponent).font(.body.weight(.medium))
            Text(url.path).font(.caption).foregroundStyle(.secondary).textSelection(.enabled)
          }
          Spacer()
          Button { state.removeInput(url) } label: { Image(systemName: "minus.circle") }
            .buttonStyle(.borderless).accessibilityLabel("Remove \(url.lastPathComponent)")
          }
          if let error = state.inputErrors[url] {
            Text(error).font(.caption).foregroundStyle(.red)
          } else if let summary = state.inputSummaries[url] {
            if state.engine == .primer3 {
              if summary.isAlignment {
                Picker("Template row", selection: Binding<Int?>(
                  get: { state.templateRowIndices[url] },
                  set: { state.templateRowIndices[url] = $0 })) {
                  Text("Choose a row…").tag(nil as Int?)
                  ForEach(Array(summary.recordTitles.enumerated()), id: \.offset) { index, title in
                    Text("\(index + 1). \(title)").tag(Optional(index))
                  }
                }
              } else {
                DisclosureGroup("Records: \(state.selectedRecordIndices[url, default: []].count) of \(summary.recordTitles.count) selected") {
                  VStack(alignment: .leading, spacing: 4) {
                    ForEach(Array(summary.recordTitles.enumerated()), id: \.offset) { index, title in
                      Toggle("\(index + 1). \(title)", isOn: Binding(
                        get: { state.selectedRecordIndices[url, default: []].contains(index) },
                        set: { checked in
                          if checked { state.selectedRecordIndices[url, default: []].insert(index) }
                          else { state.selectedRecordIndices[url, default: []].remove(index) }
                        }))
                    }
                  }.padding(.top, 6)
                }
              }
            } else {
              Text("\(summary.recordTitles.count) alignment rows included").font(.caption).foregroundStyle(.secondary)
            }
          } else { Text("Reading records…").font(.caption).foregroundStyle(.secondary) }
        }.padding(10).background(.quaternary.opacity(0.3), in: RoundedRectangle(cornerRadius: 6))
      }
      if !state.inputURLs.isEmpty {
        Text("\(state.inputURLs.count) input \(state.inputURLs.count == 1 ? "file" : "files"). Record numbers distinguish repeated names.")
          .font(.caption).foregroundStyle(.secondary)
      }
    }
  }

  private var primer3Section: some View {
    VStack(alignment: .leading, spacing: 14) {
      Text("Design settings").font(.headline)
      Picker("Assay", selection: $state.chemistry) {
        ForEach(PrimerDesignChemistry.allCases) { Text($0.rawValue).tag($0) }
      }
      if state.chemistry == .hydrolysisProbe {
        Text("Pick an internal oligo with each pair. Reporter, quencher and vendor modifications are assigned after sequence design.")
          .font(.caption).foregroundStyle(.secondary)
      }
      HStack {
        numberField("Product minimum (bp)", $state.productSizeMin)
        numberField("Product maximum (bp)", $state.productSizeMax)
        numberField("Candidate pairs", $state.pairCount)
      }
      Toggle("Amplify a specific region", isOn: $state.targetEnabled)
      if state.targetEnabled {
        HStack {
          numberField("Target start", $state.targetStart)
          numberField("Target end", $state.targetEnd)
        }
        Text("Coordinates are 1-based and inclusive on each ungapped template. Primers must flank the region.")
          .font(.caption).foregroundStyle(.secondary)
      }
      if state.inputSummaries.values.contains(where: \.isAlignment) {
        Toggle("Require binding sites conserved across all alignment rows", isOn: $state.conservedBindingSites)
        Text("Exclude variable and gapped columns from primer and probe binding sites on the chosen template.")
          .font(.caption).foregroundStyle(.secondary)
      }
    }
  }

  private var schemeSection: some View {
    VStack(alignment: .leading, spacing: 14) {
      Text("Scheme settings").font(.headline)
      Picker("Output grouping", selection: $state.grouping) {
        Text("One scheme per MSA").tag(PrimerAnalysisGrouping.independent)
        Text("Combined scheme from selected MSAs").tag(PrimerAnalysisGrouping.combined)
      }
      Text(state.grouping == .independent
        ? "Each alignment produces a separate scheme and retains its input identity."
        : "Run PrimalScheme3-LGE custom fork panel-create once with all selected alignments to design a combined panel.")
        .font(.caption).foregroundStyle(.secondary)
      if state.grouping == .combined {
        Text("Combined panel mode: Equal. Reference identifiers are normalized for execution, with a stored mapping to the original allele names.")
          .font(.caption).foregroundStyle(.secondary)
      }
      HStack {
        numberField("Amplicon size (bp)", $state.ampliconSize)
        numberField("Primer pools", $state.poolCount)
      }
    }
  }

  private var advancedSection: some View {
    DisclosureGroup("Advanced settings", isExpanded: $state.advancedExpanded) {
      VStack(alignment: .leading, spacing: 14) {
        if state.engine == .primer3 {
          Text("Primer length (nt)").font(.subheadline.weight(.medium))
          HStack {
            numberField("Minimum", $state.primerMinSize)
            numberField("Optimum", $state.primerOptSize)
            numberField("Maximum", $state.primerMaxSize)
          }
          Text("Primer melting temperature (°C)").font(.subheadline.weight(.medium))
          HStack {
            numberField("Minimum", $state.primerMinTm)
            numberField("Optimum", $state.primerOptTm)
            numberField("Maximum", $state.primerMaxTm)
          }
          HStack {
            numberField("Minimum GC (%)", $state.primerMinGC)
            numberField("Maximum GC (%)", $state.primerMaxGC)
          }
        } else {
          HStack {
            numberField("Minimum base frequency (0–1)", $state.minimumBaseFrequency)
            numberField("CPU cores", $state.coreCount)
          }
          if state.grouping == .independent { numberField("Minimum overlap (bp)", $state.minOverlap) }
          Toggle("Use high-GC design settings", isOn: $state.highGC)
          Text("Mapping reference: first alignment row. Original allele names are retained in the analysis.")
            .font(.caption).foregroundStyle(.secondary)
          Toggle("Treat uncovered alignment ends as missing observations", isOn: $state.excludeUncoveredEnds)
          Text("PrimalScheme3-LGE custom fork: excludes missing terminal observations at each candidate site while retaining available internal sequence. Uses Python discovery with the selected CPU count. Turn off for legacy Rust behavior. Unobserved alleles are not evidence of a match.")
            .font(.caption).foregroundStyle(.secondary)
        }
        TextField("Executable override (optional)", text: $state.executableOverride)
          .textFieldStyle(.roundedBorder)
        Text("Leave blank to use the optional managed tool pack.")
          .font(.caption).foregroundStyle(.secondary)
      }.padding(.top, 12)
    }
  }

  private var outputSection: some View {
    VStack(alignment: .leading, spacing: 10) {
      Text("Save analysis").font(.headline)
      TextField("Analysis name", text: $state.analysisName).textFieldStyle(.roundedBorder)
      HStack {
        Text(state.destinationURL?.path ?? "No destination selected")
          .font(.caption).foregroundStyle(.secondary).textSelection(.enabled)
        Spacer()
        Button("Choose…", action: chooseDestination)
      }
      Text("The bundle preserves inputs, native outputs, result links, settings and reproducibility provenance.")
        .font(.caption).foregroundStyle(.secondary)
    }
  }

  private var footer: some View {
    HStack(spacing: 12) {
      if state.isRunning { ProgressView().controlSize(.small) }
      VStack(alignment: .leading, spacing: 4) {
        if let error = state.errorMessage {
          Text(error).foregroundStyle(.red).textSelection(.enabled)
        } else {
          Text(state.progressMessage ?? state.validationMessage ?? state.inputReadinessMessage ?? "Ready to design.")
            .foregroundStyle(.secondary)
        }
      }.font(.callout).frame(maxWidth: .infinity, alignment: .leading)
      if state.isRunning {
        Button("Cancel Run", action: onCancelRun)
      } else {
        Button("Close", action: onClose).keyboardShortcut(.cancelAction)
        if let result = state.completedURL {
          Button("Open Results") { onOpenResult(result) }
        }
        Button(state.completedURL == nil ? "Design" : "Design Again", action: onRun)
          .disabled(state.validationMessage != nil || state.inputReadinessMessage != nil)
          .keyboardShortcut(.defaultAction)
      }
    }
  }

  private func numberField(_ title: String, _ value: Binding<String>) -> some View {
    VStack(alignment: .leading, spacing: 5) {
      Text(title).font(.caption).foregroundStyle(.secondary)
      TextField(title, text: value).textFieldStyle(.roundedBorder)
    }.frame(maxWidth: .infinity, alignment: .leading)
  }

  private func chooseInputs() {
    let panel = NSOpenPanel()
    panel.title = "Choose primer design inputs"
    panel.canChooseFiles = true
    panel.canChooseDirectories = true
    panel.treatsFilePackagesAsDirectories = false
    panel.allowsMultipleSelection = true
    if panel.runModal() == .OK { state.addInputs(panel.urls) }
  }

  private func chooseDestination() {
    let panel = NSSavePanel()
    panel.title = "Save primer analysis"
    panel.nameFieldStringValue = state.analysisName.replacingOccurrences(of: "/", with: "-") + ".lungfishprimeranalysis"
    panel.canCreateDirectories = true
    if panel.runModal() == .OK, let url = panel.url {
      state.destinationURL = url
    }
  }
}
