// ThirdPartyLicensesWindowController.swift - Third-party license viewer
// Copyright (c) 2024 Lungfish Contributors
// SPDX-License-Identifier: MIT

import AppKit
import LungfishCore

/// Displays the full text of third-party licenses for all embedded tools.
///
/// Opened from the About window's "Third-Party Licenses" link.
/// Follows macOS HIG: uses a standard document-style window with a monospaced
/// text view showing the complete THIRD-PARTY-NOTICES content.
@MainActor
final class ThirdPartyLicensesWindowController: NSWindowController {

    private enum AccessibilityID {
        static let window = "third-party-licenses-window"
        static let scrollView = "third-party-licenses-scroll-view"
        static let textView = "third-party-licenses-text-view"
    }

    convenience init() {
        let window = NSWindow(
            contentRect: NSRect(x: 0, y: 0, width: 600, height: 520),
            styleMask: [.titled, .closable, .resizable, .miniaturizable],
            backing: .buffered,
            defer: true
        )
        window.title = "\(LungfishAppIdentity.current.fullName) \u{2014} Third-Party Licenses"
        window.isReleasedWhenClosed = false
        window.isRestorable = false
        window.center()
        window.identifier = NSUserInterfaceItemIdentifier(AccessibilityID.window)
        window.minSize = NSSize(width: 400, height: 300)
        self.init(window: window)
        setupContent()
    }

    private func setupContent() {
        guard let window, let contentView = window.contentView else { return }

        let scrollView = NSScrollView()
        scrollView.translatesAutoresizingMaskIntoConstraints = false
        scrollView.hasVerticalScroller = true
        scrollView.hasHorizontalScroller = false
        scrollView.autohidesScrollers = true
        scrollView.borderType = .noBorder
        scrollView.drawsBackground = true
        scrollView.setAccessibilityIdentifier(AccessibilityID.scrollView)

        let textView = NSTextView()
        textView.isEditable = false
        textView.isSelectable = true
        textView.drawsBackground = true
        textView.textContainerInset = NSSize(width: 16, height: 16)
        textView.isAutomaticLinkDetectionEnabled = true
        textView.textContainer?.widthTracksTextView = true
        textView.textContainer?.containerSize = NSSize(width: 0, height: CGFloat.greatestFiniteMagnitude)
        textView.setAccessibilityIdentifier(AccessibilityID.textView)
        scrollView.documentView = textView

        contentView.addSubview(scrollView)
        NSLayoutConstraint.activate([
            scrollView.topAnchor.constraint(equalTo: contentView.topAnchor),
            scrollView.leadingAnchor.constraint(equalTo: contentView.leadingAnchor),
            scrollView.trailingAnchor.constraint(equalTo: contentView.trailingAnchor),
            scrollView.bottomAnchor.constraint(equalTo: contentView.bottomAnchor),
        ])

        let licenseText = Self.loadLicenseText()
        let attributed = NSAttributedString(
            string: licenseText,
            attributes: [
                .font: NSFont.monospacedSystemFont(ofSize: 11, weight: .regular),
                .foregroundColor: NSColor.labelColor,
            ]
        )
        textView.textStorage?.setAttributedString(attributed)
    }

    /// Loads the THIRD-PARTY-NOTICES text from the app bundle resource.
    ///
    /// The file is generated by `scripts/release/generate-notices.py` from
    /// `Package.resolved`, `bundled-payloads.json` and the tool lock, and is
    /// copied into `Contents/Resources` by the release/debug build scripts.
    /// There is deliberately no dynamic fallback here: a summary built only
    /// from the managed-tool manifest omits the bundled GPL-2.0 kernel and
    /// every compiled-in SwiftPM dependency's license, which is the defect
    /// this file's generation was built to fix (REL-03). Missing the bundled
    /// resource is a packaging bug that should be visible, not papered over.
    private static func loadLicenseText() -> String {
        if let url = Bundle.main.url(forResource: "THIRD-PARTY-NOTICES", withExtension: nil),
           let text = try? String(contentsOf: url, encoding: .utf8) {
            return text
        }

        return """
        Third-party license information is not available in this build.

        THIRD-PARTY-NOTICES was not found in the app bundle. This is a \
        packaging defect \u{2014} please report it. The file should have been \
        generated by scripts/release/generate-notices.py and copied into \
        Contents/Resources during the build.
        """
    }

    override func showWindow(_ sender: Any?) {
        window?.center()
        super.showWindow(sender)
        window?.makeKeyAndOrderFront(nil)
    }
}
