"""Generate compact Task 5 fixtures with native science and stubbed presentation only."""

from __future__ import annotations

import gzip
import hashlib
import json
import random
import shutil
import sys
import time
from contextlib import ExitStack
from pathlib import Path
from types import SimpleNamespace
from unittest.mock import patch

import numpy as np
from primalschemers import FKmer, RKmer

from primalscheme3.core.classes import PrimerPair
from primalscheme3.core.config import Config
from primalscheme3.core.logger import setup_rich_logger
from primalscheme3.core.mapping import create_mapping, ref_index_to_msa
from primalscheme3.core.seq_functions import reverse_complement
from primalscheme3.panel.coverage_pipeline import run_coverage_pipeline
from primalscheme3.panel.coverage_provenance import capabilities_document, capture_execution_identity
from primalscheme3.panel.panel_classes import PanelRunModes
from primalscheme3.panel.panel_main import panelcreate


def random_dna(seed: int, length: int) -> str:
    return "".join(random.Random(seed).choices("ACGT", k=length))


def variant(sequence: str) -> str:
    bases = {"A": "C", "C": "G", "G": "T", "T": "A"}
    result = list(sequence)
    for index in range(8, len(result), 17):
        result[index] = bases[result[index]]
    return "".join(result)


def plotdata(_views, work, **_kwargs):
    path = Path(work) / "plotdata.json.gz"
    with gzip.open(path, "wt") as stream:
        json.dump({"fixture": {"presentation": "test-only stub"}}, stream)
    return {"fixture": {"presentation": "test-only stub"}}


def presentation_stubs() -> ExitStack:
    stack = ExitStack()
    stack.enter_context(patch(
        "primalscheme3.panel.coverage_pipeline.plot_primer_thermo_profile_html",
        return_value="<html>test-only thermo presentation stub</html>",
    ))
    stack.enter_context(patch(
        "primalscheme3.panel.coverage_pipeline.generate_all_plotdata",
        side_effect=plotdata,
    ))
    stack.enter_context(patch(
        "primalscheme3.panel.coverage_pipeline.generate_all_plots_html",
        return_value="<html>test-only coverage presentation stub</html>",
    ))
    stack.enter_context(patch(
        "primalscheme3.panel.coverage_pipeline.primer_mismatch_heatmap",
        return_value="<html>test-only mismatch presentation stub</html>",
    ))
    return stack


def config() -> Config:
    return Config(
        selection_algorithm="coverage",
        terminal_gap_policy="observed-only",
        amplicon_size=200,
        amplicon_size_min=150,
        amplicon_size_max=280,
        amplicon_size_metric="reference-span",
        mismatch_product_size=2000,
        n_pools=2,
        ncores=1,
        optimizer_starts=1,
        optimizer_repair_rounds=0,
        optimizer_time_limit=5,
    )


def generation_record(
    kind: str,
    *,
    construction: str = "public panelcreate discovery",
    scientific_artifacts: str = "generated by reviewed public panelcreate coverage workflow",
) -> dict[str, object]:
    return {
        "schemaVersion": "lungfish.test-fixture-generation/v1",
        "generator": "PrimalScheme3CoverageFixtureGenerator.py",
        "nativeToolVersion": config().version,
        "scientificArtifacts": scientific_artifacts,
        "scientificFixture": kind,
        "candidateConstruction": construction,
        "scientificMocks": "none",
        "presentationArtifacts": "test-only deterministic stubs",
    }


def argv(sources: list[Path], output: Path, caps: bool, *, mismatch_product_size: int = 2000) -> list[str]:
    result = ["primalscheme3", "panel-create"]
    for source in sources:
        result += ["--msa", str(source.resolve())]
    result += [
        "--output", str(output.resolve()), "--mode", "equal",
        "--selection-algorithm", "coverage", "--terminal-gap-policy", "observed-only",
        "--amplicon-size", "200", "--amplicon-size-min", "150",
        "--amplicon-size-max", "280", "--n-pools", "2", "--ncores", "1",
        "--use-matchdb", "--offline-plots", "--coverage-metric", "full-span",
        "--coverage-target", "0.9", "--optimizer-seed", "0",
        "--optimizer-starts", "1", "--optimizer-repair-rounds", "0",
        "--optimizer-time-limit", "5", "--mispriming-product-size", str(mismatch_product_size),
    ]
    if caps:
        result += ["--max-amplicons", "0", "--max-amplicons-msa", "0"]
    return result


def generate(output: Path, sources: list[Path], *, caps: bool, kind: str) -> None:
    if output.exists():
        shutil.rmtree(output)
    (output / "work").mkdir(parents=True)
    (output / "work" / "fixture-generation.json").write_text(
        json.dumps(generation_record(kind), sort_keys=True) + "\n"
    )
    with presentation_stubs():
        panelcreate(
            msa=sources,
            output_dir=output,
            config=config(),
            pm=None,
            force=True,
            mode=PanelRunModes.EQUAL,
            max_amplicons=0 if caps else None,
            max_amplicons_msa=0 if caps else None,
            offline_plots=True,
            executed_argv=argv(sources, output, caps),
        )


def uncertain_sequence() -> str:
    generator = random.Random(12345)
    sequence = ""
    for _ in range(8):
        sequence = "".join(generator.choice("ACGT") for _ in range(240))
    return sequence


def generate_uncertain(output: Path, source: Path) -> None:
    if output.exists():
        shutil.rmtree(output)
    (output / "work").mkdir(parents=True)
    (output / "work" / "fixture-generation.json").write_text(json.dumps(generation_record(
        "mixed-length primer cloud with fresh joint-row uncertainty at D=199",
        construction=(
            "explicit deterministic candidate built with real native FKmer/RKmer; "
            "normal build_catalog, optimizer, fresh validator, exports and provenance"
        ),
        scientific_artifacts=(
            "generated by reviewed public build_catalog and run_coverage_pipeline APIs; "
            "optimizer, fresh validator, scientific exports and provenance are native"
        ),
    ), sort_keys=True) + "\n")

    sequence = uncertain_sequence()
    rows = [sequence, "N" + sequence[1:]]
    array = np.array([list(row) for row in rows], dtype="U1")
    mapping, array = create_mapping(array, 0)
    pair = PrimerPair(
        FKmer([sequence[:24].encode(), sequence[1:24].encode()], 24, [0.5, 0.5]),
        RKmer([reverse_complement(sequence[176:200]).encode()], 176, [1.0]),
        0,
    )
    msa = SimpleNamespace(
        array=array,
        _mapping_array=mapping,
        _ref_to_msa=ref_index_to_msa(mapping),
        _seq_dict={"fixture_reference": rows[0], "fixture_uncertain": rows[1]},
        primerpairs=[pair],
        fkmers=[pair.fprimer],
        rkmers=[pair.rprimer],
        msa_index=0,
        name="fixture-uncertain",
        _chrom_name="fixture_uncertain_reference",
        regions=None,
    )
    config_value = Config(
        selection_algorithm="coverage",
        terminal_gap_policy="observed-only",
        amplicon_size=200,
        amplicon_size_min=150,
        amplicon_size_max=280,
        amplicon_size_metric="reference-span",
        mismatch_product_size=199,
        n_pools=2,
        ncores=1,
        optimizer_starts=1,
        optimizer_repair_rounds=0,
        optimizer_time_limit=5,
    )
    config_value.discovery_workers_by_msa = {0: 1}
    stored = output / "work" / "0000-fixture-uncertain.fasta"
    execution_start = capture_execution_identity([source])
    shutil.copyfile(source, stored)
    msa_data = {0: {
        "msa_path": "work/0000-fixture-uncertain.fasta",
        "msa_name": "fixture-uncertain",
        "msa_chromname": "fixture_uncertain_reference",
        "msa_uuid": "synthetic-d199",
        "msa_checksum": hashlib.md5(source.read_bytes()).hexdigest(),
    }}
    config_dict = {
        **config_value.to_dict(),
        "mode": "equal",
        "max_amplicons": None,
        "max_amplicons_msa": None,
        "max_amplicons_region_group": None,
        "region_bedfile": None,
        "input_bedfile": None,
        "discovery_core_count": 1,
        "discovery_workers_by_msa": {"0": 1},
    }
    logger = setup_rich_logger(str(output / "work" / "file.log"))
    with presentation_stubs():
        run_coverage_pipeline(
            msa_dict={0: msa},
            msa_data=msa_data,
            input_records=[{
                "sourcePath": str(source.resolve()),
                "storedPath": "work/0000-fixture-uncertain.fasta",
                "sourceIndex": 0,
            }],
            output_dir=output,
            config=config_value,
            config_dict=config_dict,
            max_amplicons=None,
            max_amplicons_msa=None,
            offline_plots=True,
            logger=logger,
            argv=argv([source], output, False, mismatch_product_size=199),
            started_at=time.monotonic(),
            execution_start=execution_start,
        )


def main(selected: Path) -> None:
    resources = selected.parent
    capabilities = resources / "PrimalScheme3CoverageCapabilities.json"
    empty = resources / "PrimalScheme3CoverageNativeEmpty"
    uncertain_output = resources / "PrimalScheme3CoverageNativeUncertain"
    selected_source = resources / "fixture-source.fasta"
    empty_sources = [resources / "fixture-empty-a.fasta", resources / "fixture-empty-b.fasta"]
    uncertain_source = resources / "fixture-uncertain.fasta"
    sequence = random_dna(1127, 500)
    selected_source.write_text(
        f">fixture-reference\n{sequence}\n>fixture-variant\n{variant(sequence)}\n"
    )
    for source, seed, length in zip(empty_sources, [2201, 2202], [180, 183]):
        source.write_text(f">{source.stem}\n{random_dna(seed, length)}\n")
    uncertain = uncertain_sequence()
    uncertain_source.write_text(
        f">fixture-reference\n{uncertain}\n>fixture-uncertain\nN{uncertain[1:]}\n"
    )
    try:
        capabilities.write_text(json.dumps(capabilities_document(), sort_keys=True) + "\n")
        generate(selected, [selected_source], caps=False, kind="selected multi-member primer clouds")
        generate(empty, empty_sources, caps=True, kind="valid two-input literal-zero-cap assignment")
        generate_uncertain(uncertain_output, uncertain_source)
    finally:
        selected_source.unlink(missing_ok=True)
        for source in empty_sources:
            source.unlink(missing_ok=True)
        uncertain_source.unlink(missing_ok=True)
    print(selected)
    print(empty)
    print(uncertain_output)


if __name__ == "__main__":
    main(Path(sys.argv[1]))
