"""Generate compact Task 5 fixtures with native science and stubbed presentation only."""

from __future__ import annotations

import gzip
import json
import random
import shutil
import sys
from contextlib import ExitStack
from pathlib import Path
from unittest.mock import patch

from primalscheme3.core.config import Config
from primalscheme3.panel.coverage_provenance import capabilities_document
from primalscheme3.panel.panel_classes import PanelRunModes
from primalscheme3.panel.panel_main import panelcreate


def random_dna(seed: int, length: int) -> str:
    return "".join(random.Random(seed).choices("ACGT", k=length))


def variant(sequence: str) -> str:
    bases = {"A": "C", "C": "G", "G": "T", "T": "A"}
    result = list(sequence)
    for index in range(8, len(result), 17):
        result[index] = bases[result[index]]
    return "".join(result)


def plotdata(_views, work, **_kwargs):
    path = Path(work) / "plotdata.json.gz"
    with gzip.open(path, "wt") as stream:
        json.dump({"fixture": {"presentation": "test-only stub"}}, stream)
    return {"fixture": {"presentation": "test-only stub"}}


def presentation_stubs() -> ExitStack:
    stack = ExitStack()
    stack.enter_context(patch(
        "primalscheme3.panel.coverage_pipeline.plot_primer_thermo_profile_html",
        return_value="<html>test-only thermo presentation stub</html>",
    ))
    stack.enter_context(patch(
        "primalscheme3.panel.coverage_pipeline.generate_all_plotdata",
        side_effect=plotdata,
    ))
    stack.enter_context(patch(
        "primalscheme3.panel.coverage_pipeline.generate_all_plots_html",
        return_value="<html>test-only coverage presentation stub</html>",
    ))
    stack.enter_context(patch(
        "primalscheme3.panel.coverage_pipeline.primer_mismatch_heatmap",
        return_value="<html>test-only mismatch presentation stub</html>",
    ))
    return stack


def config() -> Config:
    return Config(
        selection_algorithm="coverage",
        terminal_gap_policy="observed-only",
        amplicon_size=200,
        amplicon_size_min=150,
        amplicon_size_max=280,
        amplicon_size_metric="reference-span",
        mismatch_product_size=2000,
        n_pools=2,
        ncores=1,
        optimizer_starts=1,
        optimizer_repair_rounds=0,
        optimizer_time_limit=5,
    )


def generation_record(kind: str) -> dict[str, object]:
    return {
        "schemaVersion": "lungfish.test-fixture-generation/v1",
        "generator": "PrimalScheme3CoverageFixtureGenerator.py",
        "nativeToolVersion": config().version,
        "scientificArtifacts": "generated by reviewed public panelcreate coverage workflow",
        "scientificFixture": kind,
        "presentationArtifacts": "test-only deterministic stubs",
    }


def argv(sources: list[Path], output: Path, caps: bool) -> list[str]:
    result = ["primalscheme3", "panel-create"]
    for source in sources:
        result += ["--msa", str(source.resolve())]
    result += [
        "--output", str(output.resolve()), "--mode", "equal",
        "--selection-algorithm", "coverage", "--terminal-gap-policy", "observed-only",
        "--amplicon-size", "200", "--amplicon-size-min", "150",
        "--amplicon-size-max", "280", "--n-pools", "2", "--ncores", "1",
        "--use-matchdb", "--offline-plots", "--coverage-metric", "full-span",
        "--coverage-target", "0.9", "--optimizer-seed", "0",
        "--optimizer-starts", "1", "--optimizer-repair-rounds", "0",
        "--optimizer-time-limit", "5", "--mispriming-product-size", "2000",
    ]
    if caps:
        result += ["--max-amplicons", "0", "--max-amplicons-msa", "0"]
    return result


def generate(output: Path, sources: list[Path], *, caps: bool, kind: str) -> None:
    if output.exists():
        shutil.rmtree(output)
    (output / "work").mkdir(parents=True)
    (output / "work" / "fixture-generation.json").write_text(
        json.dumps(generation_record(kind), sort_keys=True) + "\n"
    )
    with presentation_stubs():
        panelcreate(
            msa=sources,
            output_dir=output,
            config=config(),
            pm=None,
            force=True,
            mode=PanelRunModes.EQUAL,
            max_amplicons=0 if caps else None,
            max_amplicons_msa=0 if caps else None,
            offline_plots=True,
            executed_argv=argv(sources, output, caps),
        )


def main(selected: Path) -> None:
    resources = selected.parent
    capabilities = resources / "PrimalScheme3CoverageCapabilities.json"
    empty = resources / "PrimalScheme3CoverageNativeEmpty"
    selected_source = resources / "fixture-source.fasta"
    empty_sources = [resources / "fixture-empty-a.fasta", resources / "fixture-empty-b.fasta"]
    sequence = random_dna(1127, 500)
    selected_source.write_text(
        f">fixture-reference\n{sequence}\n>fixture-variant\n{variant(sequence)}\n"
    )
    for source, seed in zip(empty_sources, [2201, 2202]):
        source.write_text(f">{source.stem}\n{random_dna(seed, 180)}\n")
    try:
        capabilities.write_text(json.dumps(capabilities_document(), sort_keys=True) + "\n")
        generate(selected, [selected_source], caps=False, kind="selected multi-member primer clouds")
        generate(empty, empty_sources, caps=True, kind="valid two-input literal-zero-cap assignment")
    finally:
        selected_source.unlink(missing_ok=True)
        for source in empty_sources:
            source.unlink(missing_ok=True)
    print(selected)
    print(empty)


if __name__ == "__main__":
    main(Path(sys.argv[1]))
