// NextflowExporter.swift - Export workflow graph to Nextflow DSL2
// Copyright (c) 2024 Lungfish Contributors
// SPDX-License-Identifier: MIT

import Foundation

// MARK: - NextflowExporter

/// Exports a workflow graph to Nextflow DSL2 format.
///
/// Generates a complete Nextflow pipeline script with:
/// - Process definitions for each node
/// - Channel definitions for data flow
/// - Workflow block connecting processes
///
/// ## Example
/// ```swift
/// let exporter = NextflowExporter()
/// let script = try exporter.export(graph: myGraph)
/// try script.write(to: outputURL, atomically: true, encoding: .utf8)
/// ```
public struct NextflowExporter: Sendable {

    // MARK: - Configuration

    /// Configuration options for export.
    public struct Configuration: Sendable {
        /// DSL version to use
        public var dslVersion: String = "2"

        /// Whether to include comments
        public var includeComments: Bool = true

        /// Default container image
        public var defaultContainer: String? = "biocontainers/biocontainers:latest"

        /// Process execution options
        public var processOptions: ProcessOptions = ProcessOptions()

        /// Creates default configuration.
        public init() {}
    }

    /// Process execution options.
    public struct ProcessOptions: Sendable {
        /// Default CPUs per process
        public var cpus: Int = 1

        /// Default memory per process
        public var memory: String = "2.GB"

        /// Default time limit
        public var time: String = "1.h"

        /// Creates default options.
        public init() {}
    }

    /// The export configuration.
    public var configuration: Configuration

    // MARK: - Initialization

    /// Creates a new exporter with the given configuration.
    ///
    /// - Parameter configuration: Export configuration
    public init(configuration: Configuration = Configuration()) {
        self.configuration = configuration
    }

    // MARK: - Export

    /// Exports a workflow graph to Nextflow DSL2 script.
    ///
    /// - Parameter graph: The workflow graph to export
    /// - Returns: Complete Nextflow script as a string
    /// - Throws: `NextflowExportError` if export fails
    public func export(graph: WorkflowGraph) throws -> String {
        // Validate the graph first
        let issues = graph.validate()
        let errors = issues.filter { $0.severity == .error }
        if !errors.isEmpty {
            throw NextflowExportError.invalidGraph(errors.map { $0.description })
        }

        // Get nodes in topological order
        let orderedNodes: [WorkflowNode]
        do {
            orderedNodes = try graph.topologicalSort()
        } catch {
            throw NextflowExportError.cycleDetected
        }

        var script = ""

        // Add header
        script += generateHeader(graph: graph)
        script += "\n"

        // Add DSL2 declaration
        script += "nextflow.enable.dsl = \(configuration.dslVersion)\n\n"

        // Add parameters section
        script += generateParameters(nodes: orderedNodes)
        script += "\n"

        // Add process definitions
        for node in orderedNodes where node.type.category != .input {
            script += generateProcess(node: node, graph: graph)
            script += "\n"
        }

        // Add workflow block
        script += generateWorkflow(nodes: orderedNodes, graph: graph)

        return script
    }

    // MARK: - Header Generation

    private func generateHeader(graph: WorkflowGraph) -> String {
        var header = ""

        if configuration.includeComments {
            header += "#!/usr/bin/env nextflow\n"
            header += "/*\n"
            header += " * \(graph.name)\n"
            if let description = graph.description {
                header += " * \(description)\n"
            }
            header += " *\n"
            header += " * Version: \(graph.version)\n"
            if let author = graph.author {
                header += " * Author: \(author)\n"
            }
            header += " * Generated by: Lungfish Genome Explorer\n"
            header += " * Date: \(ISO8601DateFormatter().string(from: Date()))\n"
            header += " */\n"
        }

        return header
    }

    // MARK: - Parameters Generation

    private func generateParameters(nodes: [WorkflowNode]) -> String {
        var params = ""

        if configuration.includeComments {
            params += "// Pipeline parameters\n"
        }
        params += "params {\n"

        // Add input file parameters
        let inputNodes = nodes.filter { $0.type.category == .input }
        for node in inputNodes {
            let paramName = sanitizeIdentifier(node.label)
            switch node.type {
            case .fastqInput:
                params += "    \(paramName) = null  // Path to FASTQ files\n"
            case .fastaInput:
                params += "    \(paramName) = null  // Path to FASTA file\n"
            case .bamInput:
                params += "    \(paramName) = null  // Path to BAM file\n"
            case .sampleSheet:
                params += "    \(paramName) = null  // Path to sample sheet\n"
            default:
                break
            }
        }

        // Add output directory
        params += "    outdir = './results'\n"

        params += "}\n"

        return params
    }

    // MARK: - Process Generation

    private func generateProcess(node: WorkflowNode, graph: WorkflowGraph) -> String {
        var process = ""

        let processName = sanitizeIdentifier(node.label)

        if configuration.includeComments {
            process += "/*\n"
            process += " * Process: \(node.label)\n"
            process += " * Type: \(node.type.displayName)\n"
            process += " */\n"
        }

        process += "process \(processName) {\n"

        // Add labels and directives
        process += "    label '\(node.type.rawValue)'\n"

        // Add container if specified
        if let container = containerForNodeType(node.type) {
            process += "    container '\(container)'\n"
        }

        // Add resource requirements
        process += "    cpus \(configuration.processOptions.cpus)\n"
        process += "    memory '\(configuration.processOptions.memory)'\n"
        process += "    time '\(configuration.processOptions.time)'\n"
        process += "\n"

        // Add publish directive for output nodes
        if node.type.category == .output {
            process += "    publishDir params.outdir, mode: 'copy'\n\n"
        }

        // Add input declaration
        if !node.inputPorts.isEmpty {
            process += "    input:\n"
            for port in node.inputPorts {
                let channelType = channelTypeForPort(port)
                process += "    \(channelType) \(port.id)\n"
            }
            process += "\n"
        }

        // Add output declaration
        if !node.outputPorts.isEmpty {
            process += "    output:\n"
            for port in node.outputPorts {
                let channelType = channelTypeForPort(port)
                let pattern = outputPatternForPort(port, nodeType: node.type)
                process += "    \(channelType) \(pattern), emit: \(port.id)\n"
            }
            process += "\n"
        }

        // Add script section
        process += "    script:\n"
        process += "    \"\"\"\n"
        process += generateScript(for: node)
        process += "    \"\"\"\n"

        process += "}\n"

        return process
    }

    private func containerForNodeType(_ type: WorkflowNodeType) -> String? {
        switch type {
        case .qualityControl:
            return "quay.io/biocontainers/fastqc:0.11.9--hdfd78af_1"
        case .trimming:
            return "quay.io/biocontainers/fastp:0.23.2--h79da9fb_0"
        case .alignment:
            return "quay.io/biocontainers/bwa:0.7.17--h5bf99c6_8"
        case .variantCalling:
            return "quay.io/biocontainers/bcftools:1.15--h0ea216a_2"
        case .quantification:
            return "quay.io/biocontainers/subread:2.0.1--hed695b0_0"
        case .assembly:
            return "quay.io/biocontainers/spades:3.15.4--h95f258a_0"
        case .report:
            return "quay.io/biocontainers/multiqc:1.13--pyhdfd78af_0"
        default:
            return configuration.defaultContainer
        }
    }

    private func channelTypeForPort(_ port: NodePort) -> String {
        switch port.dataType {
        case .fastq, .fasta, .bam, .vcf:
            return "path"
        case .csv, .tsv:
            return "path"
        case .html:
            return "path"
        case .any:
            return "val"
        }
    }

    private func outputPatternForPort(_ port: NodePort, nodeType: WorkflowNodeType) -> String {
        switch port.dataType {
        case .fastq:
            return "\"*.{fastq,fq,fastq.gz,fq.gz}\""
        case .fasta:
            return "\"*.{fasta,fa,fna,fasta.gz}\""
        case .bam:
            return "\"*.{bam,cram}\""
        case .vcf:
            return "\"*.{vcf,vcf.gz}\""
        case .csv:
            return "\"*.csv\""
        case .tsv:
            return "\"*.{tsv,txt}\""
        case .html:
            return "\"*.html\""
        case .any:
            return "\"*\""
        }
    }

    private func generateScript(for node: WorkflowNode) -> String {
        switch node.type {
        case .qualityControl:
            return "    fastqc --outdir . ${reads}\n"
        case .trimming:
            return "    fastp -i ${reads} -o trimmed.fastq.gz --html report.html\n"
        case .alignment:
            return """
                bwa index ${reference}
                bwa mem -t ${task.cpus} ${reference} ${reads} | \\
                    samtools sort -@ ${task.cpus} -o aligned.bam -
                samtools index aligned.bam

            """
        case .variantCalling:
            return """
                bcftools mpileup -f ${reference} ${alignments} | \\
                    bcftools call -mv -Oz -o variants.vcf.gz
                bcftools index variants.vcf.gz

            """
        case .quantification:
            return "    featureCounts -a ${annotation} -o counts.tsv ${alignments}\n"
        case .assembly:
            return "    spades.py -s ${reads} -o assembly_output\n    mv assembly_output/contigs.fasta .\n"
        case .report:
            return "    multiqc . -o .\n"
        case .export:
            return "    cp ${input} .\n"
        default:
            return "    # TODO: Add script for \(node.type.displayName)\n"
        }
    }

    // MARK: - Workflow Generation

    private func generateWorkflow(nodes: [WorkflowNode], graph: WorkflowGraph) -> String {
        var workflow = ""

        if configuration.includeComments {
            workflow += "// Main workflow\n"
        }

        workflow += "workflow {\n"

        // Create input channels
        let inputNodes = nodes.filter { $0.type.category == .input }
        for node in inputNodes {
            let channelName = sanitizeIdentifier(node.label) + "_ch"
            let paramName = sanitizeIdentifier(node.label)
            workflow += "    \(channelName) = Channel.fromPath(params.\(paramName))\n"
        }

        if !inputNodes.isEmpty {
            workflow += "\n"
        }

        // Call processes in order
        let processNodes = nodes.filter { $0.type.category != .input }
        for node in processNodes {
            let processName = sanitizeIdentifier(node.label)

            // Build input arguments from connections
            var inputArgs: [String] = []
            for port in node.inputPorts {
                let incomingConnections = graph.incomingConnections(to: node.id)
                    .filter { $0.targetPortId == port.id }

                if let connection = incomingConnections.first {
                    if let sourceNode = graph.getNode(connection.sourceNodeId) {
                        if sourceNode.type.category == .input {
                            // Reference input channel
                            inputArgs.append(sanitizeIdentifier(sourceNode.label) + "_ch")
                        } else {
                            // Reference output from another process
                            let sourceProcessName = sanitizeIdentifier(sourceNode.label)
                            inputArgs.append("\(sourceProcessName).out.\(connection.sourcePortId)")
                        }
                    }
                }
            }

            let argsString = inputArgs.joined(separator: ", ")
            workflow += "    \(processName)(\(argsString))\n"
        }

        workflow += "}\n"

        return workflow
    }

    // MARK: - Utilities

    private func sanitizeIdentifier(_ name: String) -> String {
        // Replace spaces and special characters with underscores
        var sanitized = name.replacingOccurrences(of: " ", with: "_")
        sanitized = sanitized.replacingOccurrences(of: "-", with: "_")

        // Remove any remaining non-alphanumeric characters (except underscore)
        sanitized = sanitized.filter { $0.isLetter || $0.isNumber || $0 == "_" }

        // Ensure it starts with a letter
        if let first = sanitized.first, first.isNumber {
            sanitized = "_" + sanitized
        }

        // Convert to lowercase
        return sanitized.lowercased()
    }
}

// MARK: - NextflowExportError

/// Errors that can occur during Nextflow export.
public enum NextflowExportError: Error, LocalizedError, Sendable {
    case invalidGraph([String])
    case cycleDetected
    case unsupportedNodeType(WorkflowNodeType)

    public var errorDescription: String? {
        switch self {
        case .invalidGraph(let issues):
            return "Invalid workflow graph: \(issues.joined(separator: "; "))"
        case .cycleDetected:
            return "Workflow contains cycles and cannot be exported"
        case .unsupportedNodeType(let type):
            return "Unsupported node type for Nextflow export: \(type.displayName)"
        }
    }
}
