// SnakemakeExporter.swift - Export workflow graph to Snakemake format
// Copyright (c) 2024 Lungfish Contributors
// SPDX-License-Identifier: MIT

import Foundation

// MARK: - SnakemakeExporter

/// Exports a workflow graph to Snakemake format.
///
/// Generates a complete Snakefile with:
/// - Configuration section
/// - Rule definitions for each node
/// - Input/output dependencies
///
/// ## Example
/// ```swift
/// let exporter = SnakemakeExporter()
/// let snakefile = try exporter.export(graph: myGraph)
/// try snakefile.write(to: outputURL, atomically: true, encoding: .utf8)
/// ```
public struct SnakemakeExporter: Sendable {

    // MARK: - Configuration

    /// Configuration options for export.
    public struct Configuration: Sendable {
        /// Whether to include comments
        public var includeComments: Bool = true

        /// Whether to use conda environments
        public var useConda: Bool = false

        /// Whether to use containers (Singularity/Apptainer)
        public var useContainers: Bool = true

        /// Default number of threads
        public var defaultThreads: Int = 1

        /// Default memory in MB
        public var defaultMemoryMB: Int = 2048

        /// Creates default configuration.
        public init() {}
    }

    /// The export configuration.
    public var configuration: Configuration

    // MARK: - Initialization

    /// Creates a new exporter with the given configuration.
    ///
    /// - Parameter configuration: Export configuration
    public init(configuration: Configuration = Configuration()) {
        self.configuration = configuration
    }

    // MARK: - Export

    /// Exports a workflow graph to Snakemake format.
    ///
    /// - Parameter graph: The workflow graph to export
    /// - Returns: Complete Snakefile content as a string
    /// - Throws: `SnakemakeExportError` if export fails
    public func export(graph: WorkflowGraph) throws -> String {
        // Validate the graph first
        let issues = graph.validate()
        let errors = issues.filter { $0.severity == .error }
        if !errors.isEmpty {
            throw SnakemakeExportError.invalidGraph(errors.map { $0.description })
        }

        // Get nodes in topological order
        let orderedNodes: [WorkflowNode]
        do {
            orderedNodes = try graph.topologicalSort()
        } catch {
            throw SnakemakeExportError.cycleDetected
        }

        var snakefile = ""

        // Add header
        snakefile += generateHeader(graph: graph)
        snakefile += "\n"

        // Add configuration
        snakefile += generateConfigSection(nodes: orderedNodes)
        snakefile += "\n"

        // Add rule all (target rule)
        snakefile += generateRuleAll(nodes: orderedNodes, graph: graph)
        snakefile += "\n"

        // Add rule definitions
        for node in orderedNodes where node.type.category != .input {
            snakefile += generateRule(node: node, graph: graph)
            snakefile += "\n"
        }

        return snakefile
    }

    // MARK: - Header Generation

    private func generateHeader(graph: WorkflowGraph) -> String {
        var header = ""

        if configuration.includeComments {
            header += "# \(graph.name)\n"
            if let description = graph.description {
                header += "# \(description)\n"
            }
            header += "#\n"
            header += "# Version: \(graph.version)\n"
            if let author = graph.author {
                header += "# Author: \(author)\n"
            }
            header += "# Generated by: Lungfish Genome Explorer\n"
            header += "# Date: \(ISO8601DateFormatter().string(from: Date()))\n"
            header += "#\n"
            header += "# Usage: snakemake --cores 8 --use-singularity\n"
            header += "\n"
        }

        return header
    }

    // MARK: - Configuration Section

    private func generateConfigSection(nodes: [WorkflowNode]) -> String {
        var config = ""

        if configuration.includeComments {
            config += "# Configuration\n"
        }

        config += "configfile: \"config.yaml\"\n\n"

        // Define samples/inputs
        config += "# Input files (override via config.yaml or command line)\n"

        let inputNodes = nodes.filter { $0.type.category == .input }
        for node in inputNodes {
            let paramName = sanitizeIdentifier(node.label).uppercased()
            switch node.type {
            case .fastqInput:
                config += "\(paramName) = config.get(\"\(sanitizeIdentifier(node.label))\", [])\n"
            case .fastaInput:
                config += "\(paramName) = config.get(\"\(sanitizeIdentifier(node.label))\", \"\")\n"
            case .bamInput:
                config += "\(paramName) = config.get(\"\(sanitizeIdentifier(node.label))\", \"\")\n"
            case .sampleSheet:
                config += "\(paramName) = config.get(\"\(sanitizeIdentifier(node.label))\", \"\")\n"
            default:
                break
            }
        }

        config += "\n# Output directory\n"
        config += "OUTDIR = config.get(\"outdir\", \"results\")\n"

        return config
    }

    // MARK: - Rule All Generation

    private func generateRuleAll(nodes: [WorkflowNode], graph: WorkflowGraph) -> String {
        var rule = ""

        if configuration.includeComments {
            rule += "# Target rule - defines final outputs\n"
        }

        rule += "rule all:\n"
        rule += "    input:\n"

        // Find all terminal outputs
        let outputNodes = nodes.filter { $0.type.category == .output }
        if outputNodes.isEmpty {
            // Use leaf nodes (nodes with no outgoing connections)
            let leafNodes = nodes.filter { node in
                graph.outgoingConnections(from: node.id).isEmpty && node.type.category != .input
            }
            for node in leafNodes {
                for port in node.outputPorts {
                    let outputPath = outputPathForNode(node, port: port)
                    rule += "        \(outputPath),\n"
                }
            }
        } else {
            for node in outputNodes {
                let incomingConnections = graph.incomingConnections(to: node.id)
                for connection in incomingConnections {
                    if let sourceNode = graph.getNode(connection.sourceNodeId),
                       let port = sourceNode.outputPort(withId: connection.sourcePortId) {
                        let outputPath = outputPathForNode(sourceNode, port: port)
                        rule += "        \(outputPath),\n"
                    }
                }
            }
        }

        return rule
    }

    // MARK: - Rule Generation

    private func generateRule(node: WorkflowNode, graph: WorkflowGraph) -> String {
        var rule = ""

        let ruleName = sanitizeIdentifier(node.label)

        if configuration.includeComments {
            rule += "# Rule: \(node.label)\n"
            rule += "# Type: \(node.type.displayName)\n"
        }

        rule += "rule \(ruleName):\n"

        // Input section
        if !node.inputPorts.isEmpty {
            rule += "    input:\n"
            for port in node.inputPorts {
                let incomingConnections = graph.incomingConnections(to: node.id)
                    .filter { $0.targetPortId == port.id }

                if let connection = incomingConnections.first,
                   let sourceNode = graph.getNode(connection.sourceNodeId),
                   let sourcePort = sourceNode.outputPort(withId: connection.sourcePortId) {
                    if sourceNode.type.category == .input {
                        // Reference input parameter
                        rule += "        \(port.id)=\(sanitizeIdentifier(sourceNode.label).uppercased()),\n"
                    } else {
                        // Reference output from another rule
                        let outputPath = outputPathForNode(sourceNode, port: sourcePort)
                        rule += "        \(port.id)=\(outputPath),\n"
                    }
                }
            }
        }

        // Output section
        if !node.outputPorts.isEmpty {
            rule += "    output:\n"
            for port in node.outputPorts {
                let outputPath = outputPathForNode(node, port: port)
                rule += "        \(port.id)=\(outputPath),\n"
            }
        }

        // Log section
        rule += "    log:\n"
        rule += "        f\"{OUTDIR}/logs/\(ruleName).log\"\n"

        // Benchmark section
        rule += "    benchmark:\n"
        rule += "        f\"{OUTDIR}/benchmarks/\(ruleName).txt\"\n"

        // Threads
        rule += "    threads: \(configuration.defaultThreads)\n"

        // Resources
        rule += "    resources:\n"
        rule += "        mem_mb=\(configuration.defaultMemoryMB)\n"

        // Container/Conda
        if configuration.useContainers {
            if let container = containerForNodeType(node.type) {
                rule += "    singularity:\n"
                rule += "        \"\(container)\"\n"
            }
        }

        if configuration.useConda {
            if let condaEnv = condaEnvForNodeType(node.type) {
                rule += "    conda:\n"
                rule += "        \"\(condaEnv)\"\n"
            }
        }

        // Shell section
        rule += "    shell:\n"
        rule += "        \"\"\"\n"
        rule += generateShellScript(for: node)
        rule += "        \"\"\"\n"

        return rule
    }

    private func outputPathForNode(_ node: WorkflowNode, port: NodePort) -> String {
        let ruleName = sanitizeIdentifier(node.label)
        let extension_ = extensionForDataType(port.dataType)
        return "f\"{OUTDIR}/\(ruleName)/\(port.id)\(extension_)\""
    }

    private func extensionForDataType(_ dataType: PortDataType) -> String {
        switch dataType {
        case .fastq:
            return ".fastq.gz"
        case .fasta:
            return ".fasta"
        case .bam:
            return ".bam"
        case .vcf:
            return ".vcf.gz"
        case .csv:
            return ".csv"
        case .tsv:
            return ".tsv"
        case .html:
            return ".html"
        case .any:
            return ""
        }
    }

    private func containerForNodeType(_ type: WorkflowNodeType) -> String? {
        switch type {
        case .qualityControl:
            return "docker://quay.io/biocontainers/fastqc:0.11.9--hdfd78af_1"
        case .trimming:
            return "docker://quay.io/biocontainers/fastp:0.23.2--h79da9fb_0"
        case .alignment:
            return "docker://quay.io/biocontainers/bwa:0.7.17--h5bf99c6_8"
        case .variantCalling:
            return "docker://quay.io/biocontainers/bcftools:1.15--h0ea216a_2"
        case .quantification:
            return "docker://quay.io/biocontainers/subread:2.0.1--hed695b0_0"
        case .assembly:
            return "docker://quay.io/biocontainers/spades:3.15.4--h95f258a_0"
        case .report:
            return "docker://quay.io/biocontainers/multiqc:1.13--pyhdfd78af_0"
        default:
            return nil
        }
    }

    private func condaEnvForNodeType(_ type: WorkflowNodeType) -> String? {
        switch type {
        case .qualityControl:
            return "envs/fastqc.yaml"
        case .trimming:
            return "envs/fastp.yaml"
        case .alignment:
            return "envs/bwa.yaml"
        case .variantCalling:
            return "envs/bcftools.yaml"
        case .quantification:
            return "envs/subread.yaml"
        case .assembly:
            return "envs/spades.yaml"
        case .report:
            return "envs/multiqc.yaml"
        default:
            return nil
        }
    }

    private func generateShellScript(for node: WorkflowNode) -> String {
        switch node.type {
        case .qualityControl:
            return """
                    fastqc --outdir $(dirname {output.report}) {input.reads} \\
                        > {log} 2>&1

            """
        case .trimming:
            return """
                    fastp \\
                        -i {input.reads} \\
                        -o {output.trimmed} \\
                        --html {output.report} \\
                        --thread {threads} \\
                        > {log} 2>&1

            """
        case .alignment:
            return """
                    bwa index {input.reference}
                    bwa mem -t {threads} {input.reference} {input.reads} | \\
                        samtools sort -@ {threads} -o {output.alignments} -
                    samtools index {output.alignments}
                    samtools flagstat {output.alignments} > {output.stats}
                    > {log} 2>&1

            """
        case .variantCalling:
            return """
                    bcftools mpileup -f {input.reference} {input.alignments} | \\
                        bcftools call -mv -Oz -o {output.variants}
                    bcftools index {output.variants}
                    > {log} 2>&1

            """
        case .quantification:
            return """
                    featureCounts \\
                        -a {input.annotation} \\
                        -o {output.counts} \\
                        -T {threads} \\
                        {input.alignments} \\
                        > {log} 2>&1

            """
        case .assembly:
            return """
                    spades.py \\
                        -s {input.reads} \\
                        -o $(dirname {output.contigs}) \\
                        -t {threads} \\
                        > {log} 2>&1
                    mv $(dirname {output.contigs})/contigs.fasta {output.contigs}

            """
        case .report:
            return """
                    multiqc \\
                        $(dirname {input.input}) \\
                        -o $(dirname {output.report}) \\
                        > {log} 2>&1

            """
        case .export:
            return """
                    cp {input.input} {output}
                    > {log} 2>&1

            """
        default:
            return "        # TODO: Add script for \(node.type.displayName)\n"
        }
    }

    // MARK: - Utilities

    private func sanitizeIdentifier(_ name: String) -> String {
        // Replace spaces and special characters with underscores
        var sanitized = name.replacingOccurrences(of: " ", with: "_")
        sanitized = sanitized.replacingOccurrences(of: "-", with: "_")

        // Remove any remaining non-alphanumeric characters (except underscore)
        sanitized = sanitized.filter { $0.isLetter || $0.isNumber || $0 == "_" }

        // Ensure it starts with a letter
        if let first = sanitized.first, first.isNumber {
            sanitized = "_" + sanitized
        }

        // Convert to lowercase
        return sanitized.lowercased()
    }
}

// MARK: - SnakemakeExportError

/// Errors that can occur during Snakemake export.
public enum SnakemakeExportError: Error, LocalizedError, Sendable {
    case invalidGraph([String])
    case cycleDetected
    case unsupportedNodeType(WorkflowNodeType)

    public var errorDescription: String? {
        switch self {
        case .invalidGraph(let issues):
            return "Invalid workflow graph: \(issues.joined(separator: "; "))"
        case .cycleDetected:
            return "Workflow contains cycles and cannot be exported"
        case .unsupportedNodeType(let type):
            return "Unsupported node type for Snakemake export: \(type.displayName)"
        }
    }
}
